/**
 * UI strings for site navigation, the schemes search page and the scheme detail page.
 * Kept separate from vernacularDictionary.ts; getTranslation() checks both.
 * Keys missing in a language fall back to English. Use {name} placeholders for values.
 */
export const SITE_STRINGS: Record<string, Record<string, string>> = {
  en: {
    applyOnline: 'Apply online (official site)',
    applyPortal: 'Go to official portal',
    applyForm: 'Download application form',
    applyOfflineTitle: 'Apply offline',
    applyOfflineNote: 'This scheme has no online application. Apply at the office, bank or CSC named in the official steps below.',
    howToApply: 'How to apply',
    mySchemeInfoOnly: 'Scheme information page. Applications are made on the department\'s portal or office, not on myScheme.',
    clearChat: 'Clear chat',
    feedbackTitle: 'Was this information helpful?',
    feedbackYes: 'Yes',
    feedbackNo: 'No',
    feedbackThanks: 'Thanks for your feedback',
    reportWrongInfo: 'Report incorrect information',
    reportPrompt: 'What is wrong or outdated on this page?',
    reportPlaceholder: 'For example: the income limit has changed, or the link does not work',
    reportPrivacy: 'Please don\'t include your name, phone number, Aadhaar or other personal details.',
    reportSend: 'Send report',
    reportCancel: 'Cancel',
    reportThanks: 'Thank you. Your report helps us keep scheme information accurate.',
    feedbackUnavailable: 'Feedback can\'t be saved right now. Please try again later.',
    feedbackError: 'Something went wrong. Please try again.',
    prevPage: 'Previous',
    nextPage: 'Next',
    pageRange: 'Showing {from}–{to} of {total} schemes',
    pageNav: 'Scheme pages',
    goToPage: 'Go to page {page}',
    showMore: 'Show {count} more schemes',
    catStudent: 'Student / Education',
    catAgri: 'Agriculture / Farmers',
    catBiz: 'Entrepreneurship / MSME',
    catWomen: 'Women / Family Welfare',
    catSocial: 'Senior Citizens / Social Welfare',
    catSkills: 'Employment / Skill Development',
    schemeCount: '{count} Schemes',
    categoriesSubtitle: 'Explore {count} central and state government schemes grouped by beneficiary sector.',
    howItWorksBadge: 'How it works',
    genderFemale: 'Female',
    genderMale: 'Male',
    socialGeneral: 'General',
    occStudent: 'Student',
    occFarmer: 'Farmer',
    occSelfEmployed: 'Self-employed / MSME',
    occArtisan: 'Artisan / Craftsperson',
    occHomemaker: 'Homemaker',
    occRuralWorker: 'Rural worker',
    levelCentral: 'Central',
    levelState: 'State',
    officialPortalLink: 'Official myScheme Portal',
    translatedNote: 'Translated by AI from the official English text.',
    showOriginal: 'Show original (English)',
    showTranslation: 'Show translation',
    translating: 'Translating…',
    chipStudents: 'Scholarships for students',
    chipFarmers: 'Schemes for farmers',
    chipWomen: 'Schemes for women',
    chipPension: 'Pension for senior citizens',
    chipBusiness: 'Loans to start a business',
    chipJobs: 'Jobs and skill training',
    chipHowApply: 'How do I apply for {name}?',
    chipDocs: 'What documents are needed for {name}?',
    chipEligible: 'Am I eligible for {name}?',
    voiceUnavailable: 'No {lang} voice is installed on this device, so answers are shown as text. For voice, try Microsoft Edge or add the voice in Windows Settings.',
    micBlocked: 'Microphone access is blocked. Allow the microphone for this site and try again.',
    micFailed: 'Could not hear you. Check your internet connection and try again, or type your question.',
    exclusionsTitle: 'Who is not eligible',
    sourcesTitle: 'Sources & references',
    sourceCredit: 'Source: myScheme, Government of India',
    viewOnMyScheme: 'View on myScheme',
    noDocs: 'No documents are listed on the official scheme page.',
    applyModeLabel: 'Mode of application',
    stateScheme: 'State scheme',
    benefitLabel: 'Financial Benefit',
    navHome: 'Home',
    navSchemes: 'Schemes',
    navEligibility: 'Check Eligibility',
    navAskAI: 'Ask AI',
    brandTagline: 'Vernacular Scheme Assistant',
    disclaimer: 'Independent citizen assistant, not an official government website. Always apply on the official scheme portal.',
    heroSearchBtn: 'Search',
    statSchemes: 'Schemes',
    statCategories: 'Categories',
    statLanguages: 'Languages',
    homeCtaTitle: 'Not sure which schemes you qualify for?',
    homeCtaDesc: 'Answer a few simple questions and get a personalised eligibility report in about 2 minutes.',
    homeAskTitle: 'Ask in your own language',
    homeAskDesc: 'Type or speak your question to the AI assistant in any of 10 Indian languages.',
    viewAllSchemes: 'View all schemes',
    viewSchemes: 'View schemes',
    schemesTitle: 'Explore Government Schemes',
    schemesSubtitle: 'Search and filter schemes by category, eligibility and benefits.',
    filtersTitle: 'Filters',
    clearFilters: 'Clear all',
    filterCategory: 'Category',
    filterGender: 'Gender',
    filterSocialCategory: 'Social Category',
    filterOccupation: 'Occupation',
    filterAny: 'Any',
    sortBy: 'Sort by',
    sortRelevance: 'Relevance',
    sortBenefit: 'Highest benefit',
    sortName: 'Name (A–Z)',
    resultsCount: '{count} schemes found',
    noResults: 'No schemes match your search. Try removing some filters.',
    viewDetails: 'View details',
    backToSchemes: 'Back to schemes',
    tabDetails: 'Details',
    tabBenefits: 'Benefits',
    tabEligibility: 'Eligibility',
    tabApply: 'Application Process',
    tabDocuments: 'Documents Required',
    applyOfficial: 'Apply on Official Portal',
    checkEligibilityBtn: 'Check Your Eligibility',
    listenBtn: 'Listen',
    stopBtn: 'Stop',
    askAiAbout: 'Ask AI about this scheme',
    ministry: 'Ministry / Department',
    schemeLevel: 'Scheme level',
    lastChecked: 'Information last checked',
    officialWebsite: 'Official website',
    eligibilityIntro: 'You may be eligible if you meet all of these conditions:',
    eligibilityNone: 'No specific restrictions. Open to all citizens.',
    eligibilityCheckCta: 'Not sure? Answer a few questions to check if you qualify.',
    docsIntro: 'Tick the documents you already have to see what is still missing.',
    docsReady: '{ready} of {total} documents ready',
    docsAllReady: 'All documents ready. You can apply now.',
    applyHelp: 'Need help? Visit your nearest Common Service Centre (CSC) to apply in person with these documents.',
    quickFacts: 'Quick facts',
    notFound: 'Scheme not found.',
    heroSubtitleAll: 'Discover, check instant eligibility, and get guided application help for {count} central and state government schemes, using AI voice and text.',
    footerTagline: 'Helping every citizen discover, understand and apply for government schemes in their own language.',
    footerDisclaimer: 'GoodBridgeScheme AI is an independent assistant and is not affiliated with the Government of India. Scheme information is reproduced from myScheme (myscheme.gov.in), the Government of India’s official scheme platform, and official state portals; always confirm details on the official website before applying.'
  },
  hi: {
    applyOnline: 'ऑनलाइन आवेदन करें (आधिकारिक साइट)',
    applyPortal: 'आधिकारिक पोर्टल पर जाएँ',
    applyForm: 'आवेदन पत्र डाउनलोड करें',
    applyOfflineTitle: 'ऑफ़लाइन आवेदन करें',
    applyOfflineNote: 'इस योजना में ऑनलाइन आवेदन नहीं है। नीचे दिए गए आधिकारिक चरणों में बताए गए कार्यालय, बैंक या CSC पर आवेदन करें।',
    howToApply: 'आवेदन कैसे करें',
    mySchemeInfoOnly: 'योजना की जानकारी का पेज। आवेदन विभाग के पोर्टल या कार्यालय में होता है, myScheme पर नहीं।',
    clearChat: 'चैट साफ़ करें',
    feedbackTitle: 'क्या यह जानकारी उपयोगी थी?',
    feedbackYes: 'हाँ',
    feedbackNo: 'नहीं',
    feedbackThanks: 'आपकी प्रतिक्रिया के लिए धन्यवाद',
    reportWrongInfo: 'गलत जानकारी की रिपोर्ट करें',
    reportPrompt: 'इस पृष्ठ पर क्या गलत या पुराना है?',
    reportPlaceholder: 'उदाहरण: आय सीमा बदल गई है, या लिंक काम नहीं करता',
    reportPrivacy: 'कृपया अपना नाम, फ़ोन नंबर, आधार या अन्य व्यक्तिगत जानकारी न लिखें।',
    reportSend: 'रिपोर्ट भेजें',
    reportCancel: 'रद्द करें',
    reportThanks: 'धन्यवाद। आपकी रिपोर्ट योजना की जानकारी सही रखने में मदद करती है।',
    feedbackUnavailable: 'अभी प्रतिक्रिया सहेजी नहीं जा सकती। कृपया बाद में प्रयास करें।',
    feedbackError: 'कुछ गलत हो गया। कृपया फिर से प्रयास करें।',
    prevPage: 'पिछला',
    nextPage: 'अगला',
    pageRange: '{total} में से {from}–{to} योजनाएं दिखाई जा रही हैं',
    pageNav: 'योजना पृष्ठ',
    goToPage: 'पृष्ठ {page} पर जाएं',
    showMore: '{count} और योजनाएं दिखाएं',
    catStudent: 'छात्र / शिक्षा',
    catAgri: 'कृषि / किसान',
    catBiz: 'उद्यमिता / MSME',
    catWomen: 'महिला / परिवार कल्याण',
    catSocial: 'वरिष्ठ नागरिक / समाज कल्याण',
    catSkills: 'रोज़गार / कौशल विकास',
    schemeCount: '{count} योजनाएं',
    categoriesSubtitle: 'लाभार्थी वर्ग के अनुसार {count} केंद्र और राज्य सरकार की योजनाएं देखें।',
    howItWorksBadge: 'यह कैसे काम करता है',
    genderFemale: 'महिला',
    genderMale: 'पुरुष',
    socialGeneral: 'सामान्य',
    occStudent: 'छात्र',
    occFarmer: 'किसान',
    occSelfEmployed: 'स्वरोज़गार / MSME',
    occArtisan: 'कारीगर / शिल्पकार',
    occHomemaker: 'गृहिणी',
    occRuralWorker: 'ग्रामीण मज़दूर',
    levelCentral: 'केंद्र',
    levelState: 'राज्य',
    lastChecked: 'जानकारी अंतिम बार जाँची गई',
    footerTagline: 'हर नागरिक को अपनी भाषा में सरकारी योजनाएं खोजने, समझने और आवेदन करने में मदद।',
    footerDisclaimer: 'GoodBridgeScheme AI एक स्वतंत्र सहायक है और भारत सरकार से संबद्ध नहीं है। योजना की जानकारी myScheme (myscheme.gov.in), भारत सरकार के आधिकारिक योजना प्लेटफ़ॉर्म, और आधिकारिक राज्य पोर्टलों से ली गई है; आवेदन से पहले हमेशा आधिकारिक वेबसाइट पर जानकारी की पुष्टि करें।',
    officialPortalLink: 'आधिकारिक myScheme पोर्टल',
    translatedNote: 'आधिकारिक अंग्रेज़ी पाठ से AI द्वारा अनुवादित।',
    showOriginal: 'मूल (अंग्रेज़ी) दिखाएं',
    showTranslation: 'अनुवाद दिखाएं',
    translating: 'अनुवाद हो रहा है…',
    chipStudents: 'छात्रों के लिए छात्रवृत्ति',
    chipFarmers: 'किसानों के लिए योजनाएं',
    chipWomen: 'महिलाओं के लिए योजनाएं',
    chipPension: 'वरिष्ठ नागरिकों के लिए पेंशन',
    chipBusiness: 'व्यवसाय शुरू करने के लिए ऋण',
    chipJobs: 'रोज़गार और कौशल प्रशिक्षण',
    chipHowApply: '{name} के लिए आवेदन कैसे करें?',
    chipDocs: '{name} के लिए कौन से दस्तावेज़ चाहिए?',
    chipEligible: 'क्या मैं {name} के लिए पात्र हूँ?',
    voiceUnavailable: 'इस डिवाइस पर {lang} आवाज़ उपलब्ध नहीं है, इसलिए उत्तर टेक्स्ट में दिखाए जा रहे हैं। आवाज़ के लिए Microsoft Edge आज़माएं या Windows सेटिंग्स में आवाज़ जोड़ें।',
    micBlocked: 'माइक्रोफ़ोन की अनुमति बंद है। इस साइट के लिए माइक्रोफ़ोन की अनुमति दें और फिर कोशिश करें।',
    micFailed: 'आपकी आवाज़ सुनाई नहीं दी। इंटरनेट कनेक्शन जाँचें और फिर कोशिश करें, या अपना सवाल लिखें।',
    heroSubtitleAll: 'AI आवाज़ और टेक्स्ट की मदद से {count} केंद्र और राज्य सरकार की योजनाएं खोजें, तुरंत पात्रता जाँचें और आवेदन में मार्गदर्शन पाएं।',
    exclusionsTitle: 'कौन पात्र नहीं है',
    sourcesTitle: 'स्रोत और संदर्भ',
    sourceCredit: 'स्रोत: myScheme, भारत सरकार',
    viewOnMyScheme: 'myScheme पर देखें',
    noDocs: 'आधिकारिक योजना पृष्ठ पर कोई दस्तावेज़ सूचीबद्ध नहीं है।',
    applyModeLabel: 'आवेदन का तरीका',
    stateScheme: 'राज्य योजना',
    benefitLabel: 'आर्थिक लाभ',
    navHome: 'होम',
    navSchemes: 'योजनाएं',
    navEligibility: 'पात्रता जाँचें',
    navAskAI: 'AI से पूछें',
    brandTagline: 'आपकी भाषा में योजना सहायक',
    disclaimer: 'स्वतंत्र नागरिक सहायक, आधिकारिक सरकारी वेबसाइट नहीं। हमेशा आधिकारिक योजना पोर्टल पर ही आवेदन करें।',
    heroSearchBtn: 'खोजें',
    statSchemes: 'योजनाएं',
    statCategories: 'श्रेणियां',
    statLanguages: 'भाषाएं',
    homeCtaTitle: 'पता नहीं किन योजनाओं के लिए आप पात्र हैं?',
    homeCtaDesc: 'कुछ आसान सवालों के जवाब दें और लगभग 2 मिनट में अपनी पात्रता रिपोर्ट पाएं।',
    homeAskTitle: 'अपनी भाषा में पूछें',
    homeAskDesc: '10 भारतीय भाषाओं में से किसी में भी AI सहायक से लिखकर या बोलकर पूछें।',
    viewAllSchemes: 'सभी योजनाएं देखें',
    viewSchemes: 'योजनाएं देखें',
    schemesTitle: 'सरकारी योजनाएं खोजें',
    schemesSubtitle: 'श्रेणी, पात्रता और लाभ के अनुसार योजनाएं खोजें और छाँटें।',
    filtersTitle: 'फ़िल्टर',
    clearFilters: 'सभी हटाएं',
    filterCategory: 'श्रेणी',
    filterGender: 'लिंग',
    filterSocialCategory: 'सामाजिक वर्ग',
    filterOccupation: 'व्यवसाय',
    filterAny: 'कोई भी',
    sortBy: 'क्रम',
    sortRelevance: 'प्रासंगिकता',
    sortBenefit: 'सबसे अधिक लाभ',
    sortName: 'नाम (A–Z)',
    resultsCount: '{count} योजनाएं मिलीं',
    noResults: 'आपकी खोज से कोई योजना नहीं मिली। कुछ फ़िल्टर हटाकर देखें।',
    viewDetails: 'विवरण देखें',
    backToSchemes: 'योजनाओं पर वापस',
    tabDetails: 'विवरण',
    tabBenefits: 'लाभ',
    tabEligibility: 'पात्रता',
    tabApply: 'आवेदन प्रक्रिया',
    tabDocuments: 'आवश्यक दस्तावेज़',
    applyOfficial: 'आधिकारिक पोर्टल पर आवेदन करें',
    checkEligibilityBtn: 'अपनी पात्रता जाँचें',
    listenBtn: 'सुनें',
    stopBtn: 'रोकें',
    askAiAbout: 'इस योजना के बारे में AI से पूछें',
    ministry: 'मंत्रालय / विभाग',
    schemeLevel: 'योजना स्तर',
    officialWebsite: 'आधिकारिक वेबसाइट',
    eligibilityIntro: 'यदि आप ये सभी शर्तें पूरी करते हैं तो आप पात्र हो सकते हैं:',
    eligibilityNone: 'कोई विशेष शर्त नहीं। सभी नागरिकों के लिए।',
    eligibilityCheckCta: 'पक्का नहीं? कुछ सवालों के जवाब देकर अपनी पात्रता जाँचें।',
    docsIntro: 'जो दस्तावेज़ आपके पास हैं उन पर निशान लगाएं, ताकि पता चले क्या बाकी है।',
    docsReady: '{total} में से {ready} दस्तावेज़ तैयार',
    docsAllReady: 'सभी दस्तावेज़ तैयार हैं। अब आप आवेदन कर सकते हैं।',
    applyHelp: 'मदद चाहिए? इन दस्तावेज़ों के साथ अपने नज़दीकी जन सेवा केंद्र (CSC) पर जाकर आवेदन करें।',
    quickFacts: 'मुख्य जानकारी',
    notFound: 'योजना नहीं मिली।'
  },
  ta: {
    applyOnline: 'ஆன்லைனில் விண்ணப்பிக்கவும் (அதிகாரப்பூர்வ தளம்)',
    applyPortal: 'அதிகாரப்பூர்வ போர்ட்டலுக்குச் செல்லவும்',
    applyForm: 'விண்ணப்பப் படிவத்தைப் பதிவிறக்கவும்',
    applyOfflineTitle: 'நேரில் விண்ணப்பிக்கவும்',
    applyOfflineNote: 'இந்தத் திட்டத்திற்கு ஆன்லைன் விண்ணப்பம் இல்லை. கீழே உள்ள அதிகாரப்பூர்வ படிகளில் குறிப்பிட்ட அலுவலகம், வங்கி அல்லது CSC-யில் விண்ணப்பிக்கவும்.',
    howToApply: 'விண்ணப்பிக்கும் முறை',
    mySchemeInfoOnly: 'திட்டத் தகவல் பக்கம். விண்ணப்பங்கள் துறையின் போர்ட்டல் அல்லது அலுவலகத்தில் செய்யப்படும், myScheme-இல் அல்ல.',
    clearChat: 'அரட்டையை அழி',
    feedbackTitle: 'இந்தத் தகவல் உதவியாக இருந்ததா?',
    feedbackYes: 'ஆம்',
    feedbackNo: 'இல்லை',
    feedbackThanks: 'உங்கள் கருத்துக்கு நன்றி',
    reportWrongInfo: 'தவறான தகவலைப் புகாரளி',
    reportPrompt: 'இந்தப் பக்கத்தில் எது தவறு அல்லது பழையது?',
    reportPlaceholder: 'உதாரணம்: வருமான வரம்பு மாறியுள்ளது, அல்லது இணைப்பு வேலை செய்யவில்லை',
    reportPrivacy: 'உங்கள் பெயர், தொலைபேசி எண், ஆதார் அல்லது பிற தனிப்பட்ட விவரங்களைச் சேர்க்க வேண்டாம்.',
    reportSend: 'புகாரை அனுப்பு',
    reportCancel: 'ரத்து செய்',
    reportThanks: 'நன்றி. உங்கள் புகார் திட்டத் தகவலைத் துல்லியமாக வைத்திருக்க உதவுகிறது.',
    feedbackUnavailable: 'இப்போது கருத்தைச் சேமிக்க முடியவில்லை. பின்னர் முயற்சிக்கவும்.',
    feedbackError: 'ஏதோ தவறு நடந்தது. மீண்டும் முயற்சிக்கவும்.',
    prevPage: 'முந்தைய',
    nextPage: 'அடுத்து',
    pageRange: '{total} திட்டங்களில் {from}–{to} காட்டப்படுகின்றன',
    pageNav: 'திட்டப் பக்கங்கள்',
    goToPage: 'பக்கம் {page}க்குச் செல்',
    showMore: 'மேலும் {count} திட்டங்களைக் காட்டு',
    catStudent: 'மாணவர் / கல்வி',
    catAgri: 'வேளாண்மை / விவசாயிகள்',
    catBiz: 'தொழில்முனைவு / MSME',
    catWomen: 'பெண்கள் / குடும்ப நலன்',
    catSocial: 'மூத்த குடிமக்கள் / சமூக நலன்',
    catSkills: 'வேலைவாய்ப்பு / திறன் மேம்பாடு',
    schemeCount: '{count} திட்டங்கள்',
    categoriesSubtitle: 'பயனாளிப் பிரிவு வாரியாக {count} மத்திய மற்றும் மாநில அரசுத் திட்டங்களை ஆராயுங்கள்.',
    howItWorksBadge: 'இது எப்படி வேலை செய்கிறது',
    genderFemale: 'பெண்',
    genderMale: 'ஆண்',
    socialGeneral: 'பொது',
    occStudent: 'மாணவர்',
    occFarmer: 'விவசாயி',
    occSelfEmployed: 'சுயதொழில் / MSME',
    occArtisan: 'கைவினைஞர்',
    occHomemaker: 'இல்லத்தரசி',
    occRuralWorker: 'கிராமப்புறத் தொழிலாளர்',
    levelCentral: 'மத்திய',
    levelState: 'மாநில',
    lastChecked: 'தகவல் கடைசியாகச் சரிபார்க்கப்பட்டது',
    footerTagline: 'ஒவ்வொரு குடிமகனும் தங்கள் மொழியில் அரசுத் திட்டங்களைக் கண்டறிந்து, புரிந்து, விண்ணப்பிக்க உதவுகிறோம்.',
    footerDisclaimer: 'GoodBridgeScheme AI ஒரு சுயாதீன உதவியாளர்; இந்திய அரசுடன் இணைக்கப்படவில்லை. திட்டத் தகவல்கள் இந்திய அரசின் அதிகாரப்பூர்வ திட்டத் தளமான myScheme (myscheme.gov.in) மற்றும் அதிகாரப்பூர்வ மாநில இணையதளங்களிலிருந்து எடுக்கப்பட்டவை; விண்ணப்பிக்கும் முன் அதிகாரப்பூர்வ இணையதளத்தில் உறுதிப்படுத்திக் கொள்ளுங்கள்.',
    officialPortalLink: 'அதிகாரப்பூர்வ myScheme இணையதளம்',
    translatedNote: 'அதிகாரப்பூர்வ ஆங்கில உரையிலிருந்து AI மூலம் மொழிபெயர்க்கப்பட்டது.',
    showOriginal: 'மூலத்தைக் காட்டு (ஆங்கிலம்)',
    showTranslation: 'மொழிபெயர்ப்பைக் காட்டு',
    translating: 'மொழிபெயர்க்கப்படுகிறது…',
    chipStudents: 'மாணவர்களுக்கான கல்வி உதவித்தொகை',
    chipFarmers: 'விவசாயிகளுக்கான திட்டங்கள்',
    chipWomen: 'பெண்களுக்கான திட்டங்கள்',
    chipPension: 'மூத்த குடிமக்களுக்கான ஓய்வூதியம்',
    chipBusiness: 'தொழில் தொடங்க கடன்',
    chipJobs: 'வேலைவாய்ப்பு மற்றும் திறன் பயிற்சி',
    chipHowApply: '{name} திட்டத்திற்கு எப்படி விண்ணப்பிப்பது?',
    chipDocs: '{name} திட்டத்திற்கு என்ன ஆவணங்கள் தேவை?',
    chipEligible: 'நான் {name} திட்டத்திற்குத் தகுதியானவரா?',
    voiceUnavailable: 'இந்தச் சாதனத்தில் {lang} குரல் இல்லை, எனவே பதில்கள் உரையாகக் காட்டப்படுகின்றன. குரலுக்கு Microsoft Edge-ஐ முயற்சிக்கவும் அல்லது Windows அமைப்புகளில் குரலைச் சேர்க்கவும்.',
    micBlocked: 'மைக்ரோஃபோன் அனுமதி தடுக்கப்பட்டுள்ளது. இந்தத் தளத்திற்கு மைக்ரோஃபோனை அனுமதித்து மீண்டும் முயற்சிக்கவும்.',
    micFailed: 'உங்கள் குரல் கேட்கவில்லை. இணைய இணைப்பைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும், அல்லது உங்கள் கேள்வியைத் தட்டச்சு செய்யவும்.',
    heroSubtitleAll: 'AI குரல் மற்றும் உரை மூலம் {count} மத்திய மற்றும் மாநில அரசுத் திட்டங்களைக் கண்டறியுங்கள், உடனடியாகத் தகுதியைச் சரிபார்த்து, விண்ணப்ப வழிகாட்டுதலைப் பெறுங்கள்.',
    exclusionsTitle: 'யார் தகுதியற்றவர்கள்',
    sourcesTitle: 'ஆதாரங்கள் மற்றும் குறிப்புகள்',
    sourceCredit: 'ஆதாரம்: myScheme, இந்திய அரசு',
    viewOnMyScheme: 'myScheme-இல் காண்க',
    noDocs: 'அதிகாரப்பூர்வ திட்டப் பக்கத்தில் ஆவணங்கள் குறிப்பிடப்படவில்லை.',
    applyModeLabel: 'விண்ணப்ப முறை',
    stateScheme: 'மாநிலத் திட்டம்',
    benefitLabel: 'நிதி பலன்',
    navHome: 'முகப்பு',
    navSchemes: 'திட்டங்கள்',
    navEligibility: 'தகுதி சரிபார்',
    navAskAI: 'AI-யிடம் கேளுங்கள்',
    brandTagline: 'உங்கள் மொழியில் திட்ட உதவியாளர்',
    disclaimer: 'சுயாதீன குடிமக்கள் உதவியாளர், அதிகாரப்பூர்வ அரசு இணையதளம் அல்ல. எப்போதும் அதிகாரப்பூர்வ திட்ட இணையதளத்தில் விண்ணப்பிக்கவும்.',
    heroSearchBtn: 'தேடு',
    statSchemes: 'திட்டங்கள்',
    statCategories: 'வகைகள்',
    statLanguages: 'மொழிகள்',
    homeCtaTitle: 'எந்தத் திட்டங்களுக்குத் தகுதியானவர் என்று தெரியவில்லையா?',
    homeCtaDesc: 'சில எளிய கேள்விகளுக்குப் பதிலளித்து சுமார் 2 நிமிடங்களில் உங்கள் தகுதி அறிக்கையைப் பெறுங்கள்.',
    homeAskTitle: 'உங்கள் மொழியில் கேளுங்கள்',
    homeAskDesc: '10 இந்திய மொழிகளில் எதிலும் AI உதவியாளரிடம் தட்டச்சு செய்து அல்லது பேசிக் கேளுங்கள்.',
    viewAllSchemes: 'அனைத்து திட்டங்களையும் காண்க',
    viewSchemes: 'திட்டங்களைக் காண்க',
    schemesTitle: 'அரசுத் திட்டங்களை ஆராயுங்கள்',
    schemesSubtitle: 'வகை, தகுதி மற்றும் பலன்களின் அடிப்படையில் திட்டங்களைத் தேடி வடிகட்டுங்கள்.',
    filtersTitle: 'வடிப்பான்கள்',
    clearFilters: 'அனைத்தையும் நீக்கு',
    filterCategory: 'வகை',
    filterGender: 'பாலினம்',
    filterSocialCategory: 'சமூகப் பிரிவு',
    filterOccupation: 'தொழில்',
    filterAny: 'ஏதேனும்',
    sortBy: 'வரிசைப்படுத்து',
    sortRelevance: 'பொருத்தம்',
    sortBenefit: 'அதிக பலன்',
    sortName: 'பெயர் (A–Z)',
    resultsCount: '{count} திட்டங்கள் கிடைத்தன',
    noResults: 'உங்கள் தேடலுக்குப் பொருந்தும் திட்டங்கள் இல்லை. சில வடிப்பான்களை நீக்கிப் பாருங்கள்.',
    viewDetails: 'விவரங்களைக் காண்க',
    backToSchemes: 'திட்டங்களுக்குத் திரும்பு',
    tabDetails: 'விவரங்கள்',
    tabBenefits: 'பலன்கள்',
    tabEligibility: 'தகுதி',
    tabApply: 'விண்ணப்ப முறை',
    tabDocuments: 'தேவையான ஆவணங்கள்',
    applyOfficial: 'அதிகாரப்பூர்வ இணையதளத்தில் விண்ணப்பிக்கவும்',
    checkEligibilityBtn: 'உங்கள் தகுதியைச் சரிபாருங்கள்',
    listenBtn: 'கேளுங்கள்',
    stopBtn: 'நிறுத்து',
    askAiAbout: 'இந்தத் திட்டம் பற்றி AI-யிடம் கேளுங்கள்',
    ministry: 'அமைச்சகம் / துறை',
    schemeLevel: 'திட்ட நிலை',
    officialWebsite: 'அதிகாரப்பூர்வ இணையதளம்',
    eligibilityIntro: 'இந்த நிபந்தனைகள் அனைத்தையும் பூர்த்தி செய்தால் நீங்கள் தகுதியானவராக இருக்கலாம்:',
    eligibilityNone: 'குறிப்பிட்ட கட்டுப்பாடுகள் இல்லை. அனைத்து குடிமக்களுக்கும்.',
    eligibilityCheckCta: 'உறுதியாகத் தெரியவில்லையா? சில கேள்விகளுக்குப் பதிலளித்து உங்கள் தகுதியைச் சரிபாருங்கள்.',
    docsIntro: 'உங்களிடம் உள்ள ஆவணங்களைக் குறியிடுங்கள், இன்னும் தேவையானவை தெரியும்.',
    docsReady: '{total} இல் {ready} ஆவணங்கள் தயார்',
    docsAllReady: 'அனைத்து ஆவணங்களும் தயார். இப்போது விண்ணப்பிக்கலாம்.',
    applyHelp: 'உதவி தேவையா? இந்த ஆவணங்களுடன் அருகிலுள்ள பொது சேவை மையத்திற்கு (CSC) சென்று விண்ணப்பிக்கலாம்.',
    quickFacts: 'முக்கிய தகவல்கள்',
    notFound: 'திட்டம் கிடைக்கவில்லை.'
  },
  te: {
    applyOnline: 'ఆన్‌లైన్‌లో దరఖాస్తు చేయండి (అధికారిక సైట్)',
    applyPortal: 'అధికారిక పోర్టల్‌కు వెళ్లండి',
    applyForm: 'దరఖాస్తు ఫారమ్ డౌన్‌లోడ్ చేయండి',
    applyOfflineTitle: 'ఆఫ్‌లైన్‌లో దరఖాస్తు చేయండి',
    applyOfflineNote: 'ఈ పథకానికి ఆన్‌లైన్ దరఖాస్తు లేదు. క్రింది అధికారిక దశల్లో పేర్కొన్న కార్యాలయం, బ్యాంక్ లేదా CSCలో దరఖాస్తు చేయండి.',
    howToApply: 'ఎలా దరఖాస్తు చేయాలి',
    mySchemeInfoOnly: 'పథక సమాచార పేజీ. దరఖాస్తులు శాఖ పోర్టల్ లేదా కార్యాలయంలో చేయాలి, mySchemeలో కాదు.',
    clearChat: 'చాట్ క్లియర్ చేయండి',
    feedbackTitle: 'ఈ సమాచారం ఉపయోగపడిందా?',
    feedbackYes: 'అవును',
    feedbackNo: 'కాదు',
    feedbackThanks: 'మీ అభిప్రాయానికి ధన్యవాదాలు',
    reportWrongInfo: 'తప్పు సమాచారాన్ని నివేదించండి',
    reportPrompt: 'ఈ పేజీలో ఏది తప్పు లేదా పాతది?',
    reportPlaceholder: 'ఉదాహరణ: ఆదాయ పరిమితి మారింది, లేదా లింక్ పనిచేయడం లేదు',
    reportPrivacy: 'దయచేసి మీ పేరు, ఫోన్ నంబర్, ఆధార్ లేదా ఇతర వ్యక్తిగత వివరాలు రాయవద్దు.',
    reportSend: 'నివేదిక పంపండి',
    reportCancel: 'రద్దు చేయండి',
    reportThanks: 'ధన్యవాదాలు. మీ నివేదిక పథకం సమాచారాన్ని ఖచ్చితంగా ఉంచడంలో సహాయపడుతుంది.',
    feedbackUnavailable: 'ప్రస్తుతం అభిప్రాయాన్ని సేవ్ చేయలేము. దయచేసి తర్వాత ప్రయత్నించండి.',
    feedbackError: 'ఏదో తప్పు జరిగింది. దయచేసి మళ్లీ ప్రయత్నించండి.',
    prevPage: 'మునుపటి',
    nextPage: 'తదుపరి',
    pageRange: '{total} పథకాలలో {from}–{to} చూపబడుతున్నాయి',
    pageNav: 'పథకాల పేజీలు',
    goToPage: 'పేజీ {page}కి వెళ్లండి',
    showMore: 'మరో {count} పథకాలు చూపించు',
    catStudent: 'విద్యార్థి / విద్య',
    catAgri: 'వ్యవసాయం / రైతులు',
    catBiz: 'వ్యవస్థాపకత / MSME',
    catWomen: 'మహిళలు / కుటుంబ సంక్షేమం',
    catSocial: 'వృద్ధులు / సామాజిక సంక్షేమం',
    catSkills: 'ఉపాధి / నైపుణ్యాభివృద్ధి',
    schemeCount: '{count} పథకాలు',
    categoriesSubtitle: 'లబ్ధిదారుల వర్గాల వారీగా {count} కేంద్ర మరియు రాష్ట్ర ప్రభుత్వ పథకాలను అన్వేషించండి.',
    howItWorksBadge: 'ఇది ఎలా పనిచేస్తుంది',
    genderFemale: 'మహిళ',
    genderMale: 'పురుషుడు',
    socialGeneral: 'జనరల్',
    occStudent: 'విద్యార్థి',
    occFarmer: 'రైతు',
    occSelfEmployed: 'స్వయం ఉపాధి / MSME',
    occArtisan: 'చేతివృత్తుల వారు',
    occHomemaker: 'గృహిణి',
    occRuralWorker: 'గ్రామీణ కార్మికుడు',
    levelCentral: 'కేంద్ర',
    levelState: 'రాష్ట్ర',
    lastChecked: 'సమాచారం చివరిగా తనిఖీ చేయబడింది',
    footerTagline: 'ప్రతి పౌరుడు తన భాషలో ప్రభుత్వ పథకాలను కనుగొని, అర్థం చేసుకుని, దరఖాస్తు చేయడానికి సహాయం.',
    footerDisclaimer: 'GoodBridgeScheme AI ఒక స్వతంత్ర సహాయకుడు, భారత ప్రభుత్వంతో అనుబంధం లేదు. పథకాల సమాచారం భారత ప్రభుత్వ అధికారిక పథకాల వేదిక myScheme (myscheme.gov.in) మరియు అధికారిక రాష్ట్ర పోర్టల్‌ల నుండి తీసుకోబడింది; దరఖాస్తు చేసే ముందు అధికారిక వెబ్‌సైట్‌లో నిర్ధారించుకోండి.',
    officialPortalLink: 'అధికారిక myScheme పోర్టల్',
    translatedNote: 'అధికారిక ఆంగ్ల పాఠం నుండి AI ద్వారా అనువదించబడింది.',
    showOriginal: 'మూలాన్ని చూపించు (ఆంగ్లం)',
    showTranslation: 'అనువాదం చూపించు',
    translating: 'అనువదిస్తోంది…',
    chipStudents: 'విద్యార్థులకు స్కాలర్‌షిప్‌లు',
    chipFarmers: 'రైతులకు పథకాలు',
    chipWomen: 'మహిళలకు పథకాలు',
    chipPension: 'వృద్ధులకు పెన్షన్',
    chipBusiness: 'వ్యాపారం ప్రారంభించడానికి రుణాలు',
    chipJobs: 'ఉద్యోగాలు మరియు నైపుణ్య శిక్షణ',
    chipHowApply: '{name}కు ఎలా దరఖాస్తు చేయాలి?',
    chipDocs: '{name}కు ఏ పత్రాలు అవసరం?',
    chipEligible: 'నేను {name}కు అర్హుడినా?',
    voiceUnavailable: 'ఈ పరికరంలో {lang} వాయిస్ లేదు, కాబట్టి సమాధానాలు టెక్స్ట్‌గా చూపబడుతున్నాయి. వాయిస్ కోసం Microsoft Edge ప్రయత్నించండి లేదా Windows సెట్టింగ్స్‌లో వాయిస్ జోడించండి.',
    micBlocked: 'మైక్రోఫోన్ అనుమతి నిరోధించబడింది. ఈ సైట్‌కు మైక్రోఫోన్‌ను అనుమతించి మళ్లీ ప్రయత్నించండి.',
    micFailed: 'మీ మాట వినబడలేదు. ఇంటర్నెట్ కనెక్షన్ తనిఖీ చేసి మళ్లీ ప్రయత్నించండి, లేదా మీ ప్రశ్నను టైప్ చేయండి.',
    heroSubtitleAll: 'AI వాయిస్ మరియు టెక్స్ట్ ద్వారా {count} కేంద్ర మరియు రాష్ట్ర ప్రభుత్వ పథకాలను కనుగొనండి, వెంటనే అర్హతను తనిఖీ చేసి, దరఖాస్తు మార్గదర్శకత్వం పొందండి.',
    exclusionsTitle: 'ఎవరు అర్హులు కారు',
    sourcesTitle: 'మూలాలు & సూచనలు',
    sourceCredit: 'మూలం: myScheme, భారత ప్రభుత్వం',
    viewOnMyScheme: 'mySchemeలో చూడండి',
    noDocs: 'అధికారిక పథకం పేజీలో పత్రాలు ఏవీ ఇవ్వలేదు.',
    applyModeLabel: 'దరఖాస్తు విధానం',
    stateScheme: 'రాష్ట్ర పథకం',
    benefitLabel: 'ఆర్థిక ప్రయోజనం',
    navHome: 'హోమ్',
    navSchemes: 'పథకాలు',
    navEligibility: 'అర్హత తనిఖీ',
    navAskAI: 'AIని అడగండి',
    brandTagline: 'మీ భాషలో పథకాల సహాయకుడు',
    disclaimer: 'స్వతంత్ర పౌర సహాయకుడు, అధికారిక ప్రభుత్వ వెబ్‌సైట్ కాదు. ఎల్లప్పుడూ అధికారిక పథకం పోర్టల్‌లోనే దరఖాస్తు చేయండి.',
    heroSearchBtn: 'వెతకండి',
    statSchemes: 'పథకాలు',
    statCategories: 'వర్గాలు',
    statLanguages: 'భాషలు',
    homeCtaTitle: 'మీరు ఏ పథకాలకు అర్హులో తెలియదా?',
    homeCtaDesc: 'కొన్ని సులభమైన ప్రశ్నలకు సమాధానం ఇచ్చి సుమారు 2 నిమిషాల్లో మీ అర్హత నివేదికను పొందండి.',
    homeAskTitle: 'మీ భాషలోనే అడగండి',
    homeAskDesc: '10 భారతీయ భాషలలో దేనిలోనైనా AI సహాయకుడిని టైప్ చేసి లేదా మాట్లాడి అడగండి.',
    viewAllSchemes: 'అన్ని పథకాలు చూడండి',
    viewSchemes: 'పథకాలు చూడండి',
    schemesTitle: 'ప్రభుత్వ పథకాలను అన్వేషించండి',
    schemesSubtitle: 'వర్గం, అర్హత మరియు ప్రయోజనాల ఆధారంగా పథకాలను వెతకండి.',
    filtersTitle: 'ఫిల్టర్లు',
    clearFilters: 'అన్నీ తొలగించు',
    filterCategory: 'వర్గం',
    filterGender: 'లింగం',
    filterSocialCategory: 'సామాజిక వర్గం',
    filterOccupation: 'వృత్తి',
    filterAny: 'ఏదైనా',
    sortBy: 'క్రమం',
    sortRelevance: 'సంబంధితం',
    sortBenefit: 'అధిక ప్రయోజనం',
    sortName: 'పేరు (A–Z)',
    resultsCount: '{count} పథకాలు దొరికాయి',
    noResults: 'మీ శోధనకు సరిపోయే పథకాలు లేవు. కొన్ని ఫిల్టర్లు తొలగించి చూడండి.',
    viewDetails: 'వివరాలు చూడండి',
    backToSchemes: 'పథకాలకు తిరిగి',
    tabDetails: 'వివరాలు',
    tabBenefits: 'ప్రయోజనాలు',
    tabEligibility: 'అర్హత',
    tabApply: 'దరఖాస్తు విధానం',
    tabDocuments: 'అవసరమైన పత్రాలు',
    applyOfficial: 'అధికారిక పోర్టల్‌లో దరఖాస్తు చేయండి',
    checkEligibilityBtn: 'మీ అర్హతను తనిఖీ చేయండి',
    listenBtn: 'వినండి',
    stopBtn: 'ఆపండి',
    askAiAbout: 'ఈ పథకం గురించి AIని అడగండి',
    ministry: 'మంత్రిత్వ శాఖ / విభాగం',
    schemeLevel: 'పథకం స్థాయి',
    officialWebsite: 'అధికారిక వెబ్‌సైట్',
    eligibilityIntro: 'మీరు ఈ షరతులన్నీ నెరవేరిస్తే అర్హులు కావచ్చు:',
    eligibilityNone: 'ప్రత్యేక పరిమితులు లేవు. పౌరులందరికీ.',
    eligibilityCheckCta: 'ఖచ్చితంగా తెలియదా? కొన్ని ప్రశ్నలకు సమాధానం ఇచ్చి మీ అర్హతను తనిఖీ చేయండి.',
    docsIntro: 'మీ వద్ద ఉన్న పత్రాలను గుర్తించండి, ఇంకా ఏవి కావాలో తెలుస్తుంది.',
    docsReady: '{total}లో {ready} పత్రాలు సిద్ధం',
    docsAllReady: 'అన్ని పత్రాలు సిద్ధం. ఇప్పుడు దరఖాస్తు చేయవచ్చు.',
    applyHelp: 'సహాయం కావాలా? ఈ పత్రాలతో మీ సమీప కామన్ సర్వీస్ సెంటర్ (CSC)కి వెళ్లి దరఖాస్తు చేయండి.',
    quickFacts: 'ముఖ్య సమాచారం',
    notFound: 'పథకం కనబడలేదు.'
  },
  mr: {
    applyOnline: 'ऑनलाइन अर्ज करा (अधिकृत साइट)',
    applyPortal: 'अधिकृत पोर्टलवर जा',
    applyForm: 'अर्जाचा नमुना डाउनलोड करा',
    applyOfflineTitle: 'ऑफलाइन अर्ज करा',
    applyOfflineNote: 'या योजनेसाठी ऑनलाइन अर्ज नाही. खालील अधिकृत टप्प्यांमध्ये सांगितलेल्या कार्यालय, बँक किंवा CSC मध्ये अर्ज करा.',
    howToApply: 'अर्ज कसा करावा',
    mySchemeInfoOnly: 'योजनेच्या माहितीचे पान. अर्ज विभागाच्या पोर्टलवर किंवा कार्यालयात केला जातो, myScheme वर नाही.',
    clearChat: 'चॅट साफ करा',
    feedbackTitle: 'ही माहिती उपयुक्त होती का?',
    feedbackYes: 'हो',
    feedbackNo: 'नाही',
    feedbackThanks: 'तुमच्या अभिप्रायाबद्दल धन्यवाद',
    reportWrongInfo: 'चुकीची माहिती कळवा',
    reportPrompt: 'या पृष्ठावर काय चुकीचे किंवा जुने आहे?',
    reportPlaceholder: 'उदाहरण: उत्पन्न मर्यादा बदलली आहे, किंवा लिंक काम करत नाही',
    reportPrivacy: 'कृपया तुमचे नाव, फोन नंबर, आधार किंवा इतर वैयक्तिक माहिती लिहू नका.',
    reportSend: 'अहवाल पाठवा',
    reportCancel: 'रद्द करा',
    reportThanks: 'धन्यवाद. तुमचा अहवाल योजनेची माहिती अचूक ठेवण्यास मदत करतो.',
    feedbackUnavailable: 'आत्ता अभिप्राय जतन करता येत नाही. कृपया नंतर प्रयत्न करा.',
    feedbackError: 'काहीतरी चूक झाली. कृपया पुन्हा प्रयत्न करा.',
    prevPage: 'मागील',
    nextPage: 'पुढील',
    pageRange: '{total} पैकी {from}–{to} योजना दाखवत आहे',
    pageNav: 'योजना पृष्ठे',
    goToPage: 'पृष्ठ {page} वर जा',
    showMore: 'आणखी {count} योजना दाखवा',
    catStudent: 'विद्यार्थी / शिक्षण',
    catAgri: 'कृषी / शेतकरी',
    catBiz: 'उद्योजकता / MSME',
    catWomen: 'महिला / कुटुंब कल्याण',
    catSocial: 'ज्येष्ठ नागरिक / समाज कल्याण',
    catSkills: 'रोजगार / कौशल्य विकास',
    schemeCount: '{count} योजना',
    categoriesSubtitle: 'लाभार्थी गटानुसार {count} केंद्र आणि राज्य सरकारच्या योजना पहा.',
    howItWorksBadge: 'हे कसे काम करते',
    genderFemale: 'महिला',
    genderMale: 'पुरुष',
    socialGeneral: 'सर्वसाधारण',
    occStudent: 'विद्यार्थी',
    occFarmer: 'शेतकरी',
    occSelfEmployed: 'स्वयंरोजगार / MSME',
    occArtisan: 'कारागीर',
    occHomemaker: 'गृहिणी',
    occRuralWorker: 'ग्रामीण कामगार',
    levelCentral: 'केंद्र',
    levelState: 'राज्य',
    lastChecked: 'माहिती शेवटची तपासली',
    footerTagline: 'प्रत्येक नागरिकाला त्याच्या भाषेत सरकारी योजना शोधणे, समजणे आणि अर्ज करणे यासाठी मदत.',
    footerDisclaimer: 'GoodBridgeScheme AI हा एक स्वतंत्र सहाय्यक आहे आणि भारत सरकारशी संलग्न नाही. योजनांची माहिती भारत सरकारच्या अधिकृत योजना व्यासपीठ myScheme (myscheme.gov.in) आणि अधिकृत राज्य पोर्टल्सवरून घेतली आहे; अर्ज करण्यापूर्वी नेहमी अधिकृत वेबसाइटवर खात्री करा.',
    officialPortalLink: 'अधिकृत myScheme पोर्टल',
    translatedNote: 'अधिकृत इंग्रजी मजकुरावरून AI ने भाषांतरित केले.',
    showOriginal: 'मूळ (इंग्रजी) दाखवा',
    showTranslation: 'भाषांतर दाखवा',
    translating: 'भाषांतर होत आहे…',
    chipStudents: 'विद्यार्थ्यांसाठी शिष्यवृत्ती',
    chipFarmers: 'शेतकऱ्यांसाठी योजना',
    chipWomen: 'महिलांसाठी योजना',
    chipPension: 'ज्येष्ठ नागरिकांसाठी पेन्शन',
    chipBusiness: 'व्यवसाय सुरू करण्यासाठी कर्ज',
    chipJobs: 'रोजगार आणि कौशल्य प्रशिक्षण',
    chipHowApply: '{name} साठी अर्ज कसा करावा?',
    chipDocs: '{name} साठी कोणती कागदपत्रे लागतात?',
    chipEligible: 'मी {name} साठी पात्र आहे का?',
    voiceUnavailable: 'या डिव्हाइसवर {lang} आवाज उपलब्ध नाही, त्यामुळे उत्तरे मजकुरात दाखवली जात आहेत. आवाजासाठी Microsoft Edge वापरून पहा किंवा Windows सेटिंग्जमध्ये आवाज जोडा.',
    micBlocked: 'मायक्रोफोनची परवानगी बंद आहे. या साइटसाठी मायक्रोफोनला परवानगी द्या आणि पुन्हा प्रयत्न करा.',
    micFailed: 'तुमचा आवाज ऐकू आला नाही. इंटरनेट कनेक्शन तपासा आणि पुन्हा प्रयत्न करा, किंवा तुमचा प्रश्न लिहा.',
    heroSubtitleAll: 'AI आवाज आणि मजकुराच्या मदतीने {count} केंद्र आणि राज्य सरकारच्या योजना शोधा, त्वरित पात्रता तपासा आणि अर्जासाठी मार्गदर्शन मिळवा.',
    exclusionsTitle: 'कोण पात्र नाही',
    sourcesTitle: 'स्रोत आणि संदर्भ',
    sourceCredit: 'स्रोत: myScheme, भारत सरकार',
    viewOnMyScheme: 'myScheme वर पहा',
    noDocs: 'अधिकृत योजना पृष्ठावर कोणतीही कागदपत्रे दिलेली नाहीत.',
    applyModeLabel: 'अर्जाची पद्धत',
    stateScheme: 'राज्य योजना',
    benefitLabel: 'आर्थिक लाभ',
    navHome: 'मुख्यपृष्ठ',
    navSchemes: 'योजना',
    navEligibility: 'पात्रता तपासा',
    navAskAI: 'AI ला विचारा',
    brandTagline: 'तुमच्या भाषेत योजना सहाय्यक',
    disclaimer: 'स्वतंत्र नागरिक सहाय्यक, अधिकृत सरकारी वेबसाइट नाही. नेहमी अधिकृत योजना पोर्टलवरच अर्ज करा.',
    heroSearchBtn: 'शोधा',
    statSchemes: 'योजना',
    statCategories: 'श्रेणी',
    statLanguages: 'भाषा',
    homeCtaTitle: 'कोणत्या योजनांसाठी पात्र आहात हे माहीत नाही?',
    homeCtaDesc: 'काही सोप्या प्रश्नांची उत्तरे द्या आणि सुमारे 2 मिनिटांत तुमचा पात्रता अहवाल मिळवा.',
    homeAskTitle: 'तुमच्या भाषेत विचारा',
    homeAskDesc: '10 भारतीय भाषांपैकी कोणत्याही भाषेत AI सहाय्यकाला लिहून किंवा बोलून विचारा.',
    viewAllSchemes: 'सर्व योजना पहा',
    viewSchemes: 'योजना पहा',
    schemesTitle: 'सरकारी योजना शोधा',
    schemesSubtitle: 'श्रेणी, पात्रता आणि लाभांनुसार योजना शोधा आणि निवडा.',
    filtersTitle: 'फिल्टर',
    clearFilters: 'सर्व काढा',
    filterCategory: 'श्रेणी',
    filterGender: 'लिंग',
    filterSocialCategory: 'सामाजिक प्रवर्ग',
    filterOccupation: 'व्यवसाय',
    filterAny: 'कोणतेही',
    sortBy: 'क्रम',
    sortRelevance: 'संबंधितता',
    sortBenefit: 'सर्वाधिक लाभ',
    sortName: 'नाव (A–Z)',
    resultsCount: '{count} योजना सापडल्या',
    noResults: 'तुमच्या शोधाशी जुळणारी योजना नाही. काही फिल्टर काढून पहा.',
    viewDetails: 'तपशील पहा',
    backToSchemes: 'योजनांकडे परत',
    tabDetails: 'तपशील',
    tabBenefits: 'लाभ',
    tabEligibility: 'पात्रता',
    tabApply: 'अर्ज प्रक्रिया',
    tabDocuments: 'आवश्यक कागदपत्रे',
    applyOfficial: 'अधिकृत पोर्टलवर अर्ज करा',
    checkEligibilityBtn: 'तुमची पात्रता तपासा',
    listenBtn: 'ऐका',
    stopBtn: 'थांबवा',
    askAiAbout: 'या योजनेबद्दल AI ला विचारा',
    ministry: 'मंत्रालय / विभाग',
    schemeLevel: 'योजनेची पातळी',
    officialWebsite: 'अधिकृत वेबसाइट',
    eligibilityIntro: 'तुम्ही या सर्व अटी पूर्ण करत असल्यास पात्र असू शकता:',
    eligibilityNone: 'कोणतीही विशेष अट नाही. सर्व नागरिकांसाठी.',
    eligibilityCheckCta: 'खात्री नाही? काही प्रश्नांची उत्तरे देऊन तुमची पात्रता तपासा.',
    docsIntro: 'तुमच्याकडे असलेल्या कागदपत्रांवर खूण करा, म्हणजे काय बाकी आहे ते कळेल.',
    docsReady: '{total} पैकी {ready} कागदपत्रे तयार',
    docsAllReady: 'सर्व कागदपत्रे तयार आहेत. आता अर्ज करू शकता.',
    applyHelp: 'मदत हवी आहे? ही कागदपत्रे घेऊन जवळच्या आपले सरकार सेवा केंद्रात (CSC) जाऊन अर्ज करा.',
    quickFacts: 'मुख्य माहिती',
    notFound: 'योजना सापडली नाही.'
  },
  bn: {
    applyOnline: 'অনলাইনে আবেদন করুন (সরকারি সাইট)',
    applyPortal: 'সরকারি পোর্টালে যান',
    applyForm: 'আবেদনপত্র ডাউনলোড করুন',
    applyOfflineTitle: 'অফলাইনে আবেদন করুন',
    applyOfflineNote: 'এই প্রকল্পে অনলাইন আবেদন নেই। নিচের সরকারি ধাপে উল্লিখিত অফিস, ব্যাংক বা CSC-তে আবেদন করুন।',
    howToApply: 'কীভাবে আবেদন করবেন',
    mySchemeInfoOnly: 'প্রকল্পের তথ্য পাতা। আবেদন বিভাগের পোর্টাল বা অফিসে হয়, myScheme-এ নয়।',
    clearChat: 'চ্যাট মুছুন',
    feedbackTitle: 'এই তথ্য কি সহায়ক ছিল?',
    feedbackYes: 'হ্যাঁ',
    feedbackNo: 'না',
    feedbackThanks: 'আপনার মতামতের জন্য ধন্যবাদ',
    reportWrongInfo: 'ভুল তথ্য জানান',
    reportPrompt: 'এই পৃষ্ঠায় কী ভুল বা পুরোনো?',
    reportPlaceholder: 'যেমন: আয়ের সীমা বদলেছে, বা লিংক কাজ করছে না',
    reportPrivacy: 'অনুগ্রহ করে আপনার নাম, ফোন নম্বর, আধার বা অন্য ব্যক্তিগত তথ্য লিখবেন না।',
    reportSend: 'রিপোর্ট পাঠান',
    reportCancel: 'বাতিল',
    reportThanks: 'ধন্যবাদ। আপনার রিপোর্ট প্রকল্পের তথ্য সঠিক রাখতে সাহায্য করে।',
    feedbackUnavailable: 'এখন মতামত সংরক্ষণ করা যাচ্ছে না। অনুগ্রহ করে পরে চেষ্টা করুন।',
    feedbackError: 'কিছু ভুল হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।',
    prevPage: 'আগের',
    nextPage: 'পরের',
    pageRange: '{total}টির মধ্যে {from}–{to} প্রকল্প দেখানো হচ্ছে',
    pageNav: 'প্রকল্পের পৃষ্ঠা',
    goToPage: 'পৃষ্ঠা {page}-এ যান',
    showMore: 'আরও {count}টি প্রকল্প দেখান',
    catStudent: 'ছাত্র / শিক্ষা',
    catAgri: 'কৃষি / কৃষক',
    catBiz: 'উদ্যোক্তা / MSME',
    catWomen: 'মহিলা / পরিবার কল্যাণ',
    catSocial: 'প্রবীণ নাগরিক / সমাজকল্যাণ',
    catSkills: 'কর্মসংস্থান / দক্ষতা উন্নয়ন',
    schemeCount: '{count}টি প্রকল্প',
    categoriesSubtitle: 'উপকারভোগী শ্রেণি অনুযায়ী {count}টি কেন্দ্র ও রাজ্য সরকারের প্রকল্প দেখুন।',
    howItWorksBadge: 'কীভাবে কাজ করে',
    genderFemale: 'মহিলা',
    genderMale: 'পুরুষ',
    socialGeneral: 'সাধারণ',
    occStudent: 'ছাত্র',
    occFarmer: 'কৃষক',
    occSelfEmployed: 'স্বনিযুক্ত / MSME',
    occArtisan: 'কারিগর',
    occHomemaker: 'গৃহিণী',
    occRuralWorker: 'গ্রামীণ শ্রমিক',
    levelCentral: 'কেন্দ্রীয়',
    levelState: 'রাজ্য',
    lastChecked: 'তথ্য শেষবার যাচাই করা হয়েছে',
    footerTagline: 'প্রত্যেক নাগরিককে নিজের ভাষায় সরকারি প্রকল্প খুঁজে পেতে, বুঝতে ও আবেদন করতে সাহায্য।',
    footerDisclaimer: 'GoodBridgeScheme AI একটি স্বাধীন সহায়ক এবং ভারত সরকারের সঙ্গে যুক্ত নয়। প্রকল্পের তথ্য ভারত সরকারের সরকারি প্রকল্প প্ল্যাটফর্ম myScheme (myscheme.gov.in) এবং সরকারি রাজ্য পোর্টাল থেকে নেওয়া; আবেদনের আগে সর্বদা সরকারি ওয়েবসাইটে যাচাই করুন।',
    officialPortalLink: 'সরকারি myScheme পোর্টাল',
    translatedNote: 'সরকারি ইংরেজি পাঠ থেকে AI দ্বারা অনূদিত।',
    showOriginal: 'মূল (ইংরেজি) দেখান',
    showTranslation: 'অনুবাদ দেখান',
    translating: 'অনুবাদ হচ্ছে…',
    chipStudents: 'ছাত্রছাত্রীদের জন্য বৃত্তি',
    chipFarmers: 'কৃষকদের জন্য প্রকল্প',
    chipWomen: 'মহিলাদের জন্য প্রকল্প',
    chipPension: 'প্রবীণ নাগরিকদের পেনশন',
    chipBusiness: 'ব্যবসা শুরু করার ঋণ',
    chipJobs: 'চাকরি ও দক্ষতা প্রশিক্ষণ',
    chipHowApply: '{name}-এ কীভাবে আবেদন করব?',
    chipDocs: '{name}-এর জন্য কী কী নথি লাগবে?',
    chipEligible: 'আমি কি {name}-এর জন্য যোগ্য?',
    voiceUnavailable: 'এই ডিভাইসে {lang} ভয়েস নেই, তাই উত্তর লেখা আকারে দেখানো হচ্ছে। ভয়েসের জন্য Microsoft Edge ব্যবহার করুন বা Windows সেটিংসে ভয়েস যোগ করুন।',
    micBlocked: 'মাইক্রোফোনের অনুমতি বন্ধ আছে। এই সাইটের জন্য মাইক্রোফোনের অনুমতি দিন এবং আবার চেষ্টা করুন।',
    micFailed: 'আপনার কথা শোনা যায়নি। ইন্টারনেট সংযোগ দেখে আবার চেষ্টা করুন, বা আপনার প্রশ্ন লিখুন।',
    heroSubtitleAll: 'AI ভয়েস ও টেক্সটের মাধ্যমে {count}টি কেন্দ্র ও রাজ্য সরকারের প্রকল্প খুঁজুন, সঙ্গে সঙ্গে যোগ্যতা যাচাই করুন এবং আবেদনের নির্দেশনা পান।',
    exclusionsTitle: 'কারা যোগ্য নন',
    sourcesTitle: 'উৎস ও তথ্যসূত্র',
    sourceCredit: 'উৎস: myScheme, ভারত সরকার',
    viewOnMyScheme: 'myScheme-এ দেখুন',
    noDocs: 'সরকারি প্রকল্প পৃষ্ঠায় কোনো নথি উল্লেখ নেই।',
    applyModeLabel: 'আবেদনের পদ্ধতি',
    stateScheme: 'রাজ্য প্রকল্প',
    benefitLabel: 'আর্থিক সুবিধা',
    navHome: 'হোম',
    navSchemes: 'প্রকল্প',
    navEligibility: 'যোগ্যতা যাচাই',
    navAskAI: 'AI-কে জিজ্ঞাসা করুন',
    brandTagline: 'আপনার ভাষায় প্রকল্প সহায়ক',
    disclaimer: 'স্বাধীন নাগরিক সহায়ক, সরকারি ওয়েবসাইট নয়। সর্বদা সরকারি প্রকল্প পোর্টালেই আবেদন করুন।',
    heroSearchBtn: 'খুঁজুন',
    statSchemes: 'প্রকল্প',
    statCategories: 'বিভাগ',
    statLanguages: 'ভাষা',
    homeCtaTitle: 'কোন প্রকল্পের জন্য যোগ্য তা জানেন না?',
    homeCtaDesc: 'কয়েকটি সহজ প্রশ্নের উত্তর দিন এবং প্রায় 2 মিনিটে আপনার যোগ্যতা রিপোর্ট পান।',
    homeAskTitle: 'নিজের ভাষায় জিজ্ঞাসা করুন',
    homeAskDesc: '10টি ভারতীয় ভাষার যেকোনোটিতে লিখে বা বলে AI সহায়ককে জিজ্ঞাসা করুন।',
    viewAllSchemes: 'সব প্রকল্প দেখুন',
    viewSchemes: 'প্রকল্প দেখুন',
    schemesTitle: 'সরকারি প্রকল্প খুঁজুন',
    schemesSubtitle: 'বিভাগ, যোগ্যতা ও সুবিধা অনুযায়ী প্রকল্প খুঁজুন ও বাছাই করুন।',
    filtersTitle: 'ফিল্টার',
    clearFilters: 'সব মুছুন',
    filterCategory: 'বিভাগ',
    filterGender: 'লিঙ্গ',
    filterSocialCategory: 'সামাজিক শ্রেণি',
    filterOccupation: 'পেশা',
    filterAny: 'যেকোনো',
    sortBy: 'সাজান',
    sortRelevance: 'প্রাসঙ্গিকতা',
    sortBenefit: 'সর্বোচ্চ সুবিধা',
    sortName: 'নাম (A–Z)',
    resultsCount: '{count}টি প্রকল্প পাওয়া গেছে',
    noResults: 'আপনার অনুসন্ধানে কোনো প্রকল্প মেলেনি। কিছু ফিল্টার সরিয়ে দেখুন।',
    viewDetails: 'বিস্তারিত দেখুন',
    backToSchemes: 'প্রকল্পে ফিরে যান',
    tabDetails: 'বিস্তারিত',
    tabBenefits: 'সুবিধা',
    tabEligibility: 'যোগ্যতা',
    tabApply: 'আবেদন প্রক্রিয়া',
    tabDocuments: 'প্রয়োজনীয় নথি',
    applyOfficial: 'সরকারি পোর্টালে আবেদন করুন',
    checkEligibilityBtn: 'আপনার যোগ্যতা যাচাই করুন',
    listenBtn: 'শুনুন',
    stopBtn: 'থামান',
    askAiAbout: 'এই প্রকল্প সম্পর্কে AI-কে জিজ্ঞাসা করুন',
    ministry: 'মন্ত্রক / বিভাগ',
    schemeLevel: 'প্রকল্পের স্তর',
    officialWebsite: 'সরকারি ওয়েবসাইট',
    eligibilityIntro: 'এই সব শর্ত পূরণ করলে আপনি যোগ্য হতে পারেন:',
    eligibilityNone: 'কোনো বিশেষ শর্ত নেই। সব নাগরিকের জন্য।',
    eligibilityCheckCta: 'নিশ্চিত নন? কয়েকটি প্রশ্নের উত্তর দিয়ে আপনার যোগ্যতা যাচাই করুন।',
    docsIntro: 'আপনার কাছে থাকা নথিগুলিতে টিক দিন, কী বাকি আছে তা জানতে পারবেন।',
    docsReady: '{total}টির মধ্যে {ready}টি নথি প্রস্তুত',
    docsAllReady: 'সব নথি প্রস্তুত। এখন আবেদন করতে পারেন।',
    applyHelp: 'সাহায্য দরকার? এই নথিগুলি নিয়ে নিকটতম কমন সার্ভিস সেন্টারে (CSC) গিয়ে আবেদন করুন।',
    quickFacts: 'মূল তথ্য',
    notFound: 'প্রকল্প পাওয়া যায়নি।'
  },
  kn: {
    applyOnline: 'ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ (ಅಧಿಕೃತ ತಾಣ)',
    applyPortal: 'ಅಧಿಕೃತ ಪೋರ್ಟಲ್‌ಗೆ ಹೋಗಿ',
    applyForm: 'ಅರ್ಜಿ ನಮೂನೆ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    applyOfflineTitle: 'ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    applyOfflineNote: 'ಈ ಯೋಜನೆಗೆ ಆನ್‌ಲೈನ್ ಅರ್ಜಿ ಇಲ್ಲ. ಕೆಳಗಿನ ಅಧಿಕೃತ ಹಂತಗಳಲ್ಲಿ ಹೇಳಿರುವ ಕಚೇರಿ, ಬ್ಯಾಂಕ್ ಅಥವಾ CSC ಯಲ್ಲಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ.',
    howToApply: 'ಅರ್ಜಿ ಸಲ್ಲಿಸುವುದು ಹೇಗೆ',
    mySchemeInfoOnly: 'ಯೋಜನೆಯ ಮಾಹಿತಿ ಪುಟ. ಅರ್ಜಿಗಳನ್ನು ಇಲಾಖೆಯ ಪೋರ್ಟಲ್ ಅಥವಾ ಕಚೇರಿಯಲ್ಲಿ ಸಲ್ಲಿಸಲಾಗುತ್ತದೆ, myScheme ನಲ್ಲಿ ಅಲ್ಲ.',
    clearChat: 'ಚಾಟ್ ತೆರವುಗೊಳಿಸಿ',
    feedbackTitle: 'ಈ ಮಾಹಿತಿ ಉಪಯುಕ್ತವಾಗಿತ್ತೇ?',
    feedbackYes: 'ಹೌದು',
    feedbackNo: 'ಇಲ್ಲ',
    feedbackThanks: 'ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಗೆ ಧನ್ಯವಾದಗಳು',
    reportWrongInfo: 'ತಪ್ಪು ಮಾಹಿತಿಯನ್ನು ವರದಿ ಮಾಡಿ',
    reportPrompt: 'ಈ ಪುಟದಲ್ಲಿ ಯಾವುದು ತಪ್ಪು ಅಥವಾ ಹಳೆಯದು?',
    reportPlaceholder: 'ಉದಾಹರಣೆ: ಆದಾಯ ಮಿತಿ ಬದಲಾಗಿದೆ, ಅಥವಾ ಲಿಂಕ್ ಕೆಲಸ ಮಾಡುತ್ತಿಲ್ಲ',
    reportPrivacy: 'ದಯವಿಟ್ಟು ನಿಮ್ಮ ಹೆಸರು, ಫೋನ್ ಸಂಖ್ಯೆ, ಆಧಾರ್ ಅಥವಾ ಇತರ ವೈಯಕ್ತಿಕ ವಿವರಗಳನ್ನು ಬರೆಯಬೇಡಿ.',
    reportSend: 'ವರದಿ ಕಳುಹಿಸಿ',
    reportCancel: 'ರದ್ದುಮಾಡಿ',
    reportThanks: 'ಧನ್ಯವಾದಗಳು. ನಿಮ್ಮ ವರದಿ ಯೋಜನೆಯ ಮಾಹಿತಿಯನ್ನು ನಿಖರವಾಗಿಡಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.',
    feedbackUnavailable: 'ಈಗ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಉಳಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ. ದಯವಿಟ್ಟು ನಂತರ ಪ್ರಯತ್ನಿಸಿ.',
    feedbackError: 'ಏನೋ ತಪ್ಪಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    prevPage: 'ಹಿಂದಿನ',
    nextPage: 'ಮುಂದಿನ',
    pageRange: '{total} ಯೋಜನೆಗಳಲ್ಲಿ {from}–{to} ತೋರಿಸಲಾಗುತ್ತಿದೆ',
    pageNav: 'ಯೋಜನೆಯ ಪುಟಗಳು',
    goToPage: 'ಪುಟ {page} ಕ್ಕೆ ಹೋಗಿ',
    showMore: 'ಇನ್ನೂ {count} ಯೋಜನೆಗಳನ್ನು ತೋರಿಸಿ',
    catStudent: 'ವಿದ್ಯಾರ್ಥಿ / ಶಿಕ್ಷಣ',
    catAgri: 'ಕೃಷಿ / ರೈತರು',
    catBiz: 'ಉದ್ಯಮಶೀಲತೆ / MSME',
    catWomen: 'ಮಹಿಳೆಯರು / ಕುಟುಂಬ ಕಲ್ಯಾಣ',
    catSocial: 'ಹಿರಿಯ ನಾಗರಿಕರು / ಸಮಾಜ ಕಲ್ಯಾಣ',
    catSkills: 'ಉದ್ಯೋಗ / ಕೌಶಲ್ಯ ಅಭಿವೃದ್ಧಿ',
    schemeCount: '{count} ಯೋಜನೆಗಳು',
    categoriesSubtitle: 'ಫಲಾನುಭವಿ ವರ್ಗಗಳ ಪ್ರಕಾರ {count} ಕೇಂದ್ರ ಮತ್ತು ರಾಜ್ಯ ಸರ್ಕಾರದ ಯೋಜನೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ.',
    howItWorksBadge: 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
    genderFemale: 'ಮಹಿಳೆ',
    genderMale: 'ಪುರುಷ',
    socialGeneral: 'ಸಾಮಾನ್ಯ',
    occStudent: 'ವಿದ್ಯಾರ್ಥಿ',
    occFarmer: 'ರೈತ',
    occSelfEmployed: 'ಸ್ವ ಉದ್ಯೋಗ / MSME',
    occArtisan: 'ಕುಶಲಕರ್ಮಿ',
    occHomemaker: 'ಗೃಹಿಣಿ',
    occRuralWorker: 'ಗ್ರಾಮೀಣ ಕಾರ್ಮಿಕ',
    levelCentral: 'ಕೇಂದ್ರ',
    levelState: 'ರಾಜ್ಯ',
    lastChecked: 'ಮಾಹಿತಿ ಕೊನೆಯದಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    footerTagline: 'ಪ್ರತಿಯೊಬ್ಬ ನಾಗರಿಕರಿಗೂ ತಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಲು, ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ಮತ್ತು ಅರ್ಜಿ ಸಲ್ಲಿಸಲು ಸಹಾಯ.',
    footerDisclaimer: 'GoodBridgeScheme AI ಒಂದು ಸ್ವತಂತ್ರ ಸಹಾಯಕ ಮತ್ತು ಭಾರತ ಸರ್ಕಾರದೊಂದಿಗೆ ಸಂಯೋಜಿತವಾಗಿಲ್ಲ. ಯೋಜನೆಯ ಮಾಹಿತಿಯನ್ನು ಭಾರತ ಸರ್ಕಾರದ ಅಧಿಕೃತ ಯೋಜನಾ ವೇದಿಕೆ myScheme (myscheme.gov.in) ಮತ್ತು ಅಧಿಕೃತ ರಾಜ್ಯ ಪೋರ್ಟಲ್‌ಗಳಿಂದ ತೆಗೆದುಕೊಳ್ಳಲಾಗಿದೆ; ಅರ್ಜಿ ಸಲ್ಲಿಸುವ ಮೊದಲು ಯಾವಾಗಲೂ ಅಧಿಕೃತ ವೆಬ್‌ಸೈಟ್‌ನಲ್ಲಿ ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ.',
    officialPortalLink: 'ಅಧಿಕೃತ myScheme ಪೋರ್ಟಲ್',
    translatedNote: 'ಅಧಿಕೃತ ಇಂಗ್ಲಿಷ್ ಪಠ್ಯದಿಂದ AI ಮೂಲಕ ಅನುವಾದಿಸಲಾಗಿದೆ.',
    showOriginal: 'ಮೂಲ (ಇಂಗ್ಲಿಷ್) ತೋರಿಸಿ',
    showTranslation: 'ಅನುವಾದ ತೋರಿಸಿ',
    translating: 'ಅನುವಾದಿಸಲಾಗುತ್ತಿದೆ…',
    chipStudents: 'ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ವಿದ್ಯಾರ್ಥಿವೇತನ',
    chipFarmers: 'ರೈತರಿಗೆ ಯೋಜನೆಗಳು',
    chipWomen: 'ಮಹಿಳೆಯರಿಗೆ ಯೋಜನೆಗಳು',
    chipPension: 'ಹಿರಿಯ ನಾಗರಿಕರಿಗೆ ಪಿಂಚಣಿ',
    chipBusiness: 'ವ್ಯಾಪಾರ ಆರಂಭಿಸಲು ಸಾಲ',
    chipJobs: 'ಉದ್ಯೋಗ ಮತ್ತು ಕೌಶಲ್ಯ ತರಬೇತಿ',
    chipHowApply: '{name} ಗೆ ಹೇಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸುವುದು?',
    chipDocs: '{name} ಗೆ ಯಾವ ದಾಖಲೆಗಳು ಬೇಕು?',
    chipEligible: 'ನಾನು {name} ಗೆ ಅರ್ಹನೇ?',
    voiceUnavailable: 'ಈ ಸಾಧನದಲ್ಲಿ {lang} ಧ್ವನಿ ಇಲ್ಲ, ಆದ್ದರಿಂದ ಉತ್ತರಗಳನ್ನು ಪಠ್ಯವಾಗಿ ತೋರಿಸಲಾಗುತ್ತಿದೆ. ಧ್ವನಿಗಾಗಿ Microsoft Edge ಬಳಸಿ ಅಥವಾ Windows ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ ಧ್ವನಿಯನ್ನು ಸೇರಿಸಿ.',
    micBlocked: 'ಮೈಕ್ರೊಫೋನ್ ಅನುಮತಿ ನಿರ್ಬಂಧಿಸಲಾಗಿದೆ. ಈ ಸೈಟ್‌ಗೆ ಮೈಕ್ರೊಫೋನ್ ಅನುಮತಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    micFailed: 'ನಿಮ್ಮ ಧ್ವನಿ ಕೇಳಿಸಲಿಲ್ಲ. ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕ ಪರಿಶೀಲಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ, ಅಥವಾ ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಟೈಪ್ ಮಾಡಿ.',
    heroSubtitleAll: 'AI ಧ್ವನಿ ಮತ್ತು ಪಠ್ಯದ ಮೂಲಕ {count} ಕೇಂದ್ರ ಮತ್ತು ರಾಜ್ಯ ಸರ್ಕಾರದ ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ, ತಕ್ಷಣ ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಅರ್ಜಿ ಮಾರ್ಗದರ್ಶನ ಪಡೆಯಿರಿ.',
    exclusionsTitle: 'ಯಾರು ಅರ್ಹರಲ್ಲ',
    sourcesTitle: 'ಮೂಲಗಳು ಮತ್ತು ಉಲ್ಲೇಖಗಳು',
    sourceCredit: 'ಮೂಲ: myScheme, ಭಾರತ ಸರ್ಕಾರ',
    viewOnMyScheme: 'myScheme ನಲ್ಲಿ ನೋಡಿ',
    noDocs: 'ಅಧಿಕೃತ ಯೋಜನೆ ಪುಟದಲ್ಲಿ ಯಾವುದೇ ದಾಖಲೆಗಳನ್ನು ಪಟ್ಟಿ ಮಾಡಿಲ್ಲ.',
    applyModeLabel: 'ಅರ್ಜಿ ವಿಧಾನ',
    stateScheme: 'ರಾಜ್ಯ ಯೋಜನೆ',
    benefitLabel: 'ಆರ್ಥಿಕ ಪ್ರಯೋಜನ',
    navHome: 'ಮುಖಪುಟ',
    navSchemes: 'ಯೋಜನೆಗಳು',
    navEligibility: 'ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಿ',
    navAskAI: 'AI ಅನ್ನು ಕೇಳಿ',
    brandTagline: 'ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಯೋಜನೆ ಸಹಾಯಕ',
    disclaimer: 'ಸ್ವತಂತ್ರ ನಾಗರಿಕ ಸಹಾಯಕ, ಅಧಿಕೃತ ಸರ್ಕಾರಿ ವೆಬ್‌ಸೈಟ್ ಅಲ್ಲ. ಯಾವಾಗಲೂ ಅಧಿಕೃತ ಯೋಜನೆ ಪೋರ್ಟಲ್‌ನಲ್ಲೇ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ.',
    heroSearchBtn: 'ಹುಡುಕಿ',
    statSchemes: 'ಯೋಜನೆಗಳು',
    statCategories: 'ವರ್ಗಗಳು',
    statLanguages: 'ಭಾಷೆಗಳು',
    homeCtaTitle: 'ಯಾವ ಯೋಜನೆಗಳಿಗೆ ಅರ್ಹರು ಎಂದು ತಿಳಿದಿಲ್ಲವೇ?',
    homeCtaDesc: 'ಕೆಲವು ಸರಳ ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಿಸಿ ಸುಮಾರು 2 ನಿಮಿಷಗಳಲ್ಲಿ ನಿಮ್ಮ ಅರ್ಹತಾ ವರದಿ ಪಡೆಯಿರಿ.',
    homeAskTitle: 'ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲೇ ಕೇಳಿ',
    homeAskDesc: '10 ಭಾರತೀಯ ಭಾಷೆಗಳಲ್ಲಿ ಯಾವುದರಲ್ಲಾದರೂ AI ಸಹಾಯಕರನ್ನು ಟೈಪ್ ಮಾಡಿ ಅಥವಾ ಮಾತನಾಡಿ ಕೇಳಿ.',
    viewAllSchemes: 'ಎಲ್ಲಾ ಯೋಜನೆಗಳನ್ನು ನೋಡಿ',
    viewSchemes: 'ಯೋಜನೆಗಳನ್ನು ನೋಡಿ',
    schemesTitle: 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ',
    schemesSubtitle: 'ವರ್ಗ, ಅರ್ಹತೆ ಮತ್ತು ಪ್ರಯೋಜನಗಳ ಆಧಾರದ ಮೇಲೆ ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ.',
    filtersTitle: 'ಫಿಲ್ಟರ್‌ಗಳು',
    clearFilters: 'ಎಲ್ಲವನ್ನೂ ತೆರವುಗೊಳಿಸಿ',
    filterCategory: 'ವರ್ಗ',
    filterGender: 'ಲಿಂಗ',
    filterSocialCategory: 'ಸಾಮಾಜಿಕ ವರ್ಗ',
    filterOccupation: 'ಉದ್ಯೋಗ',
    filterAny: 'ಯಾವುದಾದರೂ',
    sortBy: 'ವಿಂಗಡಿಸಿ',
    sortRelevance: 'ಸಂಬಂಧಿತ',
    sortBenefit: 'ಅತಿ ಹೆಚ್ಚು ಪ್ರಯೋಜನ',
    sortName: 'ಹೆಸರು (A–Z)',
    resultsCount: '{count} ಯೋಜನೆಗಳು ಸಿಕ್ಕಿವೆ',
    noResults: 'ನಿಮ್ಮ ಹುಡುಕಾಟಕ್ಕೆ ಯಾವುದೇ ಯೋಜನೆ ಸಿಗಲಿಲ್ಲ. ಕೆಲವು ಫಿಲ್ಟರ್‌ಗಳನ್ನು ತೆಗೆದು ನೋಡಿ.',
    viewDetails: 'ವಿವರಗಳನ್ನು ನೋಡಿ',
    backToSchemes: 'ಯೋಜನೆಗಳಿಗೆ ಹಿಂತಿರುಗಿ',
    tabDetails: 'ವಿವರಗಳು',
    tabBenefits: 'ಪ್ರಯೋಜನಗಳು',
    tabEligibility: 'ಅರ್ಹತೆ',
    tabApply: 'ಅರ್ಜಿ ಪ್ರಕ್ರಿಯೆ',
    tabDocuments: 'ಅಗತ್ಯ ದಾಖಲೆಗಳು',
    applyOfficial: 'ಅಧಿಕೃತ ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    checkEligibilityBtn: 'ನಿಮ್ಮ ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಿ',
    listenBtn: 'ಕೇಳಿ',
    stopBtn: 'ನಿಲ್ಲಿಸಿ',
    askAiAbout: 'ಈ ಯೋಜನೆಯ ಬಗ್ಗೆ AI ಅನ್ನು ಕೇಳಿ',
    ministry: 'ಸಚಿವಾಲಯ / ಇಲಾಖೆ',
    schemeLevel: 'ಯೋಜನೆಯ ಮಟ್ಟ',
    officialWebsite: 'ಅಧಿಕೃತ ವೆಬ್‌ಸೈಟ್',
    eligibilityIntro: 'ನೀವು ಈ ಎಲ್ಲಾ ಷರತ್ತುಗಳನ್ನು ಪೂರೈಸಿದರೆ ಅರ್ಹರಾಗಬಹುದು:',
    eligibilityNone: 'ಯಾವುದೇ ವಿಶೇಷ ನಿರ್ಬಂಧಗಳಿಲ್ಲ. ಎಲ್ಲಾ ನಾಗರಿಕರಿಗೆ.',
    eligibilityCheckCta: 'ಖಚಿತವಿಲ್ಲವೇ? ಕೆಲವು ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಿಸಿ ನಿಮ್ಮ ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಿ.',
    docsIntro: 'ನಿಮ್ಮ ಬಳಿ ಇರುವ ದಾಖಲೆಗಳನ್ನು ಗುರುತಿಸಿ, ಇನ್ನೂ ಏನು ಬೇಕು ಎಂದು ತಿಳಿಯುತ್ತದೆ.',
    docsReady: '{total} ರಲ್ಲಿ {ready} ದಾಖಲೆಗಳು ಸಿದ್ಧ',
    docsAllReady: 'ಎಲ್ಲಾ ದಾಖಲೆಗಳು ಸಿದ್ಧ. ಈಗ ಅರ್ಜಿ ಸಲ್ಲಿಸಬಹುದು.',
    applyHelp: 'ಸಹಾಯ ಬೇಕೇ? ಈ ದಾಖಲೆಗಳೊಂದಿಗೆ ಹತ್ತಿರದ ಸಾಮಾನ್ಯ ಸೇವಾ ಕೇಂದ್ರಕ್ಕೆ (CSC) ಹೋಗಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ.',
    quickFacts: 'ಮುಖ್ಯ ಮಾಹಿತಿ',
    notFound: 'ಯೋಜನೆ ಸಿಗಲಿಲ್ಲ.'
  },
  gu: {
    applyOnline: 'ઓનલાઇન અરજી કરો (સત્તાવાર સાઇટ)',
    applyPortal: 'સત્તાવાર પોર્ટલ પર જાઓ',
    applyForm: 'અરજી ફોર્મ ડાઉનલોડ કરો',
    applyOfflineTitle: 'ઓફલાઇન અરજી કરો',
    applyOfflineNote: 'આ યોજનામાં ઓનલાઇન અરજી નથી. નીચેના સત્તાવાર પગલાંમાં જણાવેલ કચેરી, બેંક અથવા CSC પર અરજી કરો.',
    howToApply: 'અરજી કેવી રીતે કરવી',
    mySchemeInfoOnly: 'યોજનાની માહિતીનું પાનું. અરજી વિભાગના પોર્ટલ અથવા કચેરીમાં થાય છે, myScheme પર નહીં.',
    clearChat: 'ચેટ સાફ કરો',
    feedbackTitle: 'શું આ માહિતી ઉપયોગી હતી?',
    feedbackYes: 'હા',
    feedbackNo: 'ના',
    feedbackThanks: 'તમારા પ્રતિભાવ બદલ આભાર',
    reportWrongInfo: 'ખોટી માહિતીની જાણ કરો',
    reportPrompt: 'આ પાના પર શું ખોટું અથવા જૂનું છે?',
    reportPlaceholder: 'ઉદાહરણ: આવક મર્યાદા બદલાઈ ગઈ છે, અથવા લિંક કામ કરતી નથી',
    reportPrivacy: 'કૃપા કરીને તમારું નામ, ફોન નંબર, આધાર અથવા અન્ય વ્યક્તિગત વિગતો ન લખો.',
    reportSend: 'અહેવાલ મોકલો',
    reportCancel: 'રદ કરો',
    reportThanks: 'આભાર. તમારો અહેવાલ યોજનાની માહિતી સચોટ રાખવામાં મદદ કરે છે.',
    feedbackUnavailable: 'હમણાં પ્રતિભાવ સાચવી શકાતો નથી. કૃપા કરીને પછી પ્રયાસ કરો.',
    feedbackError: 'કંઈક ખોટું થયું. કૃપા કરીને ફરી પ્રયાસ કરો.',
    prevPage: 'પાછળ',
    nextPage: 'આગળ',
    pageRange: '{total} માંથી {from}–{to} યોજનાઓ બતાવી રહ્યા છીએ',
    pageNav: 'યોજનાનાં પાનાં',
    goToPage: 'પાનું {page} પર જાઓ',
    showMore: 'વધુ {count} યોજનાઓ બતાવો',
    catStudent: 'વિદ્યાર્થી / શિક્ષણ',
    catAgri: 'કૃષિ / ખેડૂતો',
    catBiz: 'ઉદ્યોગસાહસિકતા / MSME',
    catWomen: 'મહિલા / કુટુંબ કલ્યાણ',
    catSocial: 'વરિષ્ઠ નાગરિકો / સમાજ કલ્યાણ',
    catSkills: 'રોજગાર / કૌશલ્ય વિકાસ',
    schemeCount: '{count} યોજનાઓ',
    categoriesSubtitle: 'લાભાર્થી વર્ગ મુજબ {count} કેન્દ્ર અને રાજ્ય સરકારની યોજનાઓ જુઓ.',
    howItWorksBadge: 'તે કેવી રીતે કામ કરે છે',
    genderFemale: 'સ્ત્રી',
    genderMale: 'પુરુષ',
    socialGeneral: 'સામાન્ય',
    occStudent: 'વિદ્યાર્થી',
    occFarmer: 'ખેડૂત',
    occSelfEmployed: 'સ્વરોજગાર / MSME',
    occArtisan: 'કારીગર',
    occHomemaker: 'ગૃહિણી',
    occRuralWorker: 'ગ્રામીણ મજૂર',
    levelCentral: 'કેન્દ્ર',
    levelState: 'રાજ્ય',
    lastChecked: 'માહિતી છેલ્લે ચકાસવામાં આવી',
    footerTagline: 'દરેક નાગરિકને પોતાની ભાષામાં સરકારી યોજનાઓ શોધવા, સમજવા અને અરજી કરવામાં મદદ.',
    footerDisclaimer: 'GoodBridgeScheme AI એક સ્વતંત્ર સહાયક છે અને ભારત સરકાર સાથે જોડાયેલ નથી. યોજનાની માહિતી ભારત સરકારના સત્તાવાર યોજના પ્લેટફોર્મ myScheme (myscheme.gov.in) અને સત્તાવાર રાજ્ય પોર્ટલ્સમાંથી લેવામાં આવી છે; અરજી કરતા પહેલાં હંમેશા સત્તાવાર વેબસાઇટ પર ખાતરી કરો.',
    officialPortalLink: 'સત્તાવાર myScheme પોર્ટલ',
    translatedNote: 'સત્તાવાર અંગ્રેજી લખાણમાંથી AI દ્વારા અનુવાદિત.',
    showOriginal: 'મૂળ (અંગ્રેજી) બતાવો',
    showTranslation: 'અનુવાદ બતાવો',
    translating: 'અનુવાદ થઈ રહ્યો છે…',
    chipStudents: 'વિદ્યાર્થીઓ માટે શિષ્યવૃત્તિ',
    chipFarmers: 'ખેડૂતો માટે યોજનાઓ',
    chipWomen: 'મહિલાઓ માટે યોજનાઓ',
    chipPension: 'વરિષ્ઠ નાગરિકો માટે પેન્શન',
    chipBusiness: 'વ્યવસાય શરૂ કરવા માટે લોન',
    chipJobs: 'રોજગાર અને કૌશલ્ય તાલીમ',
    chipHowApply: '{name} માટે અરજી કેવી રીતે કરવી?',
    chipDocs: '{name} માટે કયા દસ્તાવેજો જોઈએ?',
    chipEligible: 'શું હું {name} માટે પાત્ર છું?',
    voiceUnavailable: 'આ ઉપકરણ પર {lang} અવાજ ઉપલબ્ધ નથી, તેથી જવાબો લખાણમાં બતાવવામાં આવે છે. અવાજ માટે Microsoft Edge અજમાવો અથવા Windows સેટિંગ્સમાં અવાજ ઉમેરો.',
    micBlocked: 'માઇક્રોફોનની પરવાનગી બંધ છે. આ સાઇટ માટે માઇક્રોફોનની પરવાનગી આપો અને ફરી પ્રયાસ કરો.',
    micFailed: 'તમારો અવાજ સંભળાયો નહીં. ઇન્ટરનેટ કનેક્શન તપાસો અને ફરી પ્રયાસ કરો, અથવા તમારો પ્રશ્ન લખો.',
    heroSubtitleAll: 'AI અવાજ અને ટેક્સ્ટની મદદથી {count} કેન્દ્ર અને રાજ્ય સરકારની યોજનાઓ શોધો, તરત પાત્રતા તપાસો અને અરજી માટે માર્ગદર્શન મેળવો.',
    exclusionsTitle: 'કોણ પાત્ર નથી',
    sourcesTitle: 'સ્રોત અને સંદર્ભો',
    sourceCredit: 'સ્રોત: myScheme, ભારત સરકાર',
    viewOnMyScheme: 'myScheme પર જુઓ',
    noDocs: 'સત્તાવાર યોજના પૃષ્ઠ પર કોઈ દસ્તાવેજો દર્શાવેલ નથી.',
    applyModeLabel: 'અરજીની રીત',
    stateScheme: 'રાજ્ય યોજના',
    benefitLabel: 'આર્થિક લાભ',
    navHome: 'હોમ',
    navSchemes: 'યોજનાઓ',
    navEligibility: 'પાત્રતા તપાસો',
    navAskAI: 'AI ને પૂછો',
    brandTagline: 'તમારી ભાષામાં યોજના સહાયક',
    disclaimer: 'સ્વતંત્ર નાગરિક સહાયક, સત્તાવાર સરકારી વેબસાઇટ નથી. હંમેશા સત્તાવાર યોજના પોર્ટલ પર જ અરજી કરો.',
    heroSearchBtn: 'શોધો',
    statSchemes: 'યોજનાઓ',
    statCategories: 'શ્રેણીઓ',
    statLanguages: 'ભાષાઓ',
    homeCtaTitle: 'કઈ યોજનાઓ માટે પાત્ર છો તે ખબર નથી?',
    homeCtaDesc: 'થોડા સરળ પ્રશ્નોના જવાબ આપો અને લગભગ 2 મિનિટમાં તમારો પાત્રતા અહેવાલ મેળવો.',
    homeAskTitle: 'તમારી ભાષામાં પૂછો',
    homeAskDesc: '10 ભારતીય ભાષાઓમાંથી કોઈપણમાં AI સહાયકને લખીને કે બોલીને પૂછો.',
    viewAllSchemes: 'બધી યોજનાઓ જુઓ',
    viewSchemes: 'યોજનાઓ જુઓ',
    schemesTitle: 'સરકારી યોજનાઓ શોધો',
    schemesSubtitle: 'શ્રેણી, પાત્રતા અને લાભ અનુસાર યોજનાઓ શોધો અને પસંદ કરો.',
    filtersTitle: 'ફિલ્ટર',
    clearFilters: 'બધું દૂર કરો',
    filterCategory: 'શ્રેણી',
    filterGender: 'લિંગ',
    filterSocialCategory: 'સામાજિક વર્ગ',
    filterOccupation: 'વ્યવસાય',
    filterAny: 'કોઈપણ',
    sortBy: 'ક્રમ',
    sortRelevance: 'સુસંગતતા',
    sortBenefit: 'સૌથી વધુ લાભ',
    sortName: 'નામ (A–Z)',
    resultsCount: '{count} યોજનાઓ મળી',
    noResults: 'તમારી શોધ સાથે કોઈ યોજના મેળ ખાતી નથી. કેટલાક ફિલ્ટર દૂર કરી જુઓ.',
    viewDetails: 'વિગતો જુઓ',
    backToSchemes: 'યોજનાઓ પર પાછા',
    tabDetails: 'વિગતો',
    tabBenefits: 'લાભ',
    tabEligibility: 'પાત્રતા',
    tabApply: 'અરજી પ્રક્રિયા',
    tabDocuments: 'જરૂરી દસ્તાવેજો',
    applyOfficial: 'સત્તાવાર પોર્ટલ પર અરજી કરો',
    checkEligibilityBtn: 'તમારી પાત્રતા તપાસો',
    listenBtn: 'સાંભળો',
    stopBtn: 'બંધ કરો',
    askAiAbout: 'આ યોજના વિશે AI ને પૂછો',
    ministry: 'મંત્રાલય / વિભાગ',
    schemeLevel: 'યોજનાનું સ્તર',
    officialWebsite: 'સત્તાવાર વેબસાઇટ',
    eligibilityIntro: 'જો તમે આ બધી શરતો પૂરી કરો તો તમે પાત્ર હોઈ શકો છો:',
    eligibilityNone: 'કોઈ ખાસ શરત નથી. બધા નાગરિકો માટે.',
    eligibilityCheckCta: 'ખાતરી નથી? થોડા પ્રશ્નોના જવાબ આપીને તમારી પાત્રતા તપાસો.',
    docsIntro: 'તમારી પાસે રહેલા દસ્તાવેજો પર નિશાન કરો, જેથી શું બાકી છે તે ખબર પડે.',
    docsReady: '{total} માંથી {ready} દસ્તાવેજો તૈયાર',
    docsAllReady: 'બધા દસ્તાવેજો તૈયાર છે. હવે અરજી કરી શકો છો.',
    applyHelp: 'મદદ જોઈએ છે? આ દસ્તાવેજો સાથે નજીકના કોમન સર્વિસ સેન્ટર (CSC) પર જઈને અરજી કરો.',
    quickFacts: 'મુખ્ય માહિતી',
    notFound: 'યોજના મળી નથી.'
  },
  ml: {
    applyOnline: 'ഓൺലൈനായി അപേക്ഷിക്കുക (ഔദ്യോഗിക സൈറ്റ്)',
    applyPortal: 'ഔദ്യോഗിക പോർട്ടലിലേക്ക് പോകുക',
    applyForm: 'അപേക്ഷാ ഫോം ഡൗൺലോഡ് ചെയ്യുക',
    applyOfflineTitle: 'ഓഫ്‌ലൈനായി അപേക്ഷിക്കുക',
    applyOfflineNote: 'ഈ പദ്ധതിക്ക് ഓൺലൈൻ അപേക്ഷയില്ല. താഴെയുള്ള ഔദ്യോഗിക ഘട്ടങ്ങളിൽ പറയുന്ന ഓഫീസ്, ബാങ്ക് അല്ലെങ്കിൽ CSC-യിൽ അപേക്ഷിക്കുക.',
    howToApply: 'എങ്ങനെ അപേക്ഷിക്കാം',
    mySchemeInfoOnly: 'പദ്ധതി വിവര പേജ്. അപേക്ഷകൾ വകുപ്പിന്റെ പോർട്ടലിലോ ഓഫീസിലോ ആണ് നൽകുന്നത്, myScheme-ൽ അല്ല.',
    clearChat: 'ചാറ്റ് മായ്ക്കുക',
    feedbackTitle: 'ഈ വിവരം ഉപകാരപ്രദമായിരുന്നോ?',
    feedbackYes: 'അതെ',
    feedbackNo: 'ഇല്ല',
    feedbackThanks: 'നിങ്ങളുടെ അഭിപ്രായത്തിന് നന്ദി',
    reportWrongInfo: 'തെറ്റായ വിവരം റിപ്പോർട്ട് ചെയ്യുക',
    reportPrompt: 'ഈ പേജിൽ എന്താണ് തെറ്റ് അല്ലെങ്കിൽ പഴയത്?',
    reportPlaceholder: 'ഉദാഹരണം: വരുമാന പരിധി മാറി, അല്ലെങ്കിൽ ലിങ്ക് പ്രവർത്തിക്കുന്നില്ല',
    reportPrivacy: 'ദയവായി നിങ്ങളുടെ പേര്, ഫോൺ നമ്പർ, ആധാർ അല്ലെങ്കിൽ മറ്റ് വ്യക്തിഗത വിവരങ്ങൾ എഴുതരുത്.',
    reportSend: 'റിപ്പോർട്ട് അയയ്ക്കുക',
    reportCancel: 'റദ്ദാക്കുക',
    reportThanks: 'നന്ദി. നിങ്ങളുടെ റിപ്പോർട്ട് പദ്ധതി വിവരങ്ങൾ കൃത്യമായി നിലനിർത്താൻ സഹായിക്കുന്നു.',
    feedbackUnavailable: 'ഇപ്പോൾ അഭിപ്രായം സംരക്ഷിക്കാനാവില്ല. ദയവായി പിന്നീട് ശ്രമിക്കുക.',
    feedbackError: 'എന്തോ പിശക് സംഭവിച്ചു. ദയവായി വീണ്ടും ശ്രമിക്കുക.',
    prevPage: 'മുമ്പത്തെ',
    nextPage: 'അടുത്തത്',
    pageRange: '{total} പദ്ധതികളിൽ {from}–{to} കാണിക്കുന്നു',
    pageNav: 'പദ്ധതി പേജുകൾ',
    goToPage: 'പേജ് {page} ലേക്ക് പോകുക',
    showMore: '{count} പദ്ധതികൾ കൂടി കാണിക്കുക',
    catStudent: 'വിദ്യാർത്ഥി / വിദ്യാഭ്യാസം',
    catAgri: 'കൃഷി / കർഷകർ',
    catBiz: 'സംരംഭകത്വം / MSME',
    catWomen: 'സ്ത്രീകൾ / കുടുംബക്ഷേമം',
    catSocial: 'മുതിർന്ന പൗരന്മാർ / സാമൂഹികക്ഷേമം',
    catSkills: 'തൊഴിൽ / നൈപുണ്യ വികസനം',
    schemeCount: '{count} പദ്ധതികൾ',
    categoriesSubtitle: 'ഗുണഭോക്തൃ വിഭാഗം അനുസരിച്ച് {count} കേന്ദ്ര, സംസ്ഥാന സർക്കാർ പദ്ധതികൾ കാണുക.',
    howItWorksBadge: 'ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു',
    genderFemale: 'സ്ത്രീ',
    genderMale: 'പുരുഷൻ',
    socialGeneral: 'ജനറൽ',
    occStudent: 'വിദ്യാർത്ഥി',
    occFarmer: 'കർഷകൻ',
    occSelfEmployed: 'സ്വയംതൊഴിൽ / MSME',
    occArtisan: 'കരകൗശലത്തൊഴിലാളി',
    occHomemaker: 'വീട്ടമ്മ',
    occRuralWorker: 'ഗ്രാമീണ തൊഴിലാളി',
    levelCentral: 'കേന്ദ്രം',
    levelState: 'സംസ്ഥാനം',
    lastChecked: 'വിവരം അവസാനമായി പരിശോധിച്ചത്',
    footerTagline: 'ഓരോ പൗരനും സ്വന്തം ഭാഷയിൽ സർക്കാർ പദ്ധതികൾ കണ്ടെത്താനും മനസ്സിലാക്കാനും അപേക്ഷിക്കാനും സഹായിക്കുന്നു.',
    footerDisclaimer: 'GoodBridgeScheme AI ഒരു സ്വതന്ത്ര സഹായിയാണ്, ഭാരത സർക്കാരുമായി ബന്ധമില്ല. പദ്ധതി വിവരങ്ങൾ ഭാരത സർക്കാരിന്റെ ഔദ്യോഗിക പദ്ധതി പ്ലാറ്റ്‌ഫോമായ myScheme (myscheme.gov.in), ഔദ്യോഗിക സംസ്ഥാന പോർട്ടലുകൾ എന്നിവയിൽ നിന്ന് എടുത്തതാണ്; അപേക്ഷിക്കുന്നതിന് മുമ്പ് എപ്പോഴും ഔദ്യോഗിക വെബ്‌സൈറ്റിൽ ഉറപ്പാക്കുക.',
    officialPortalLink: 'ഔദ്യോഗിക myScheme പോർട്ടൽ',
    translatedNote: 'ഔദ്യോഗിക ഇംഗ്ലീഷ് പാഠത്തിൽ നിന്ന് AI വിവർത്തനം ചെയ്തത്.',
    showOriginal: 'മൂലം കാണിക്കുക (ഇംഗ്ലീഷ്)',
    showTranslation: 'വിവർത്തനം കാണിക്കുക',
    translating: 'വിവർത്തനം ചെയ്യുന്നു…',
    chipStudents: 'വിദ്യാർത്ഥികൾക്കുള്ള സ്കോളർഷിപ്പുകൾ',
    chipFarmers: 'കർഷകർക്കുള്ള പദ്ധതികൾ',
    chipWomen: 'സ്ത്രീകൾക്കുള്ള പദ്ധതികൾ',
    chipPension: 'മുതിർന്ന പൗരന്മാർക്കുള്ള പെൻഷൻ',
    chipBusiness: 'ബിസിനസ് തുടങ്ങാൻ വായ്പ',
    chipJobs: 'തൊഴിലും നൈപുണ്യ പരിശീലനവും',
    chipHowApply: '{name} ന് എങ്ങനെ അപേക്ഷിക്കാം?',
    chipDocs: '{name} ന് എന്തൊക്കെ രേഖകൾ വേണം?',
    chipEligible: 'എനിക്ക് {name} ന് യോഗ്യതയുണ്ടോ?',
    voiceUnavailable: 'ഈ ഉപകരണത്തിൽ {lang} ശബ്ദം ലഭ്യമല്ല, അതിനാൽ ഉത്തരങ്ങൾ ടെക്സ്റ്റായി കാണിക്കുന്നു. ശബ്ദത്തിനായി Microsoft Edge ഉപയോഗിക്കുക അല്ലെങ്കിൽ Windows ക്രമീകരണങ്ങളിൽ ശബ്ദം ചേർക്കുക.',
    micBlocked: 'മൈക്രോഫോൺ അനുമതി തടഞ്ഞിരിക്കുന്നു. ഈ സൈറ്റിന് മൈക്രോഫോൺ അനുവദിച്ച് വീണ്ടും ശ്രമിക്കുക.',
    micFailed: 'നിങ്ങളുടെ ശബ്ദം കേട്ടില്ല. ഇന്റർനെറ്റ് കണക്ഷൻ പരിശോധിച്ച് വീണ്ടും ശ്രമിക്കുക, അല്ലെങ്കിൽ ചോദ്യം ടൈപ്പ് ചെയ്യുക.',
    heroSubtitleAll: 'AI ശബ്ദവും ടെക്സ്റ്റും ഉപയോഗിച്ച് {count} കേന്ദ്ര, സംസ്ഥാന സർക്കാർ പദ്ധതികൾ കണ്ടെത്തുക, ഉടൻ യോഗ്യത പരിശോധിക്കുക, അപേക്ഷയ്ക്കുള്ള മാർഗ്ഗനിർദ്ദേശം നേടുക.',
    exclusionsTitle: 'ആർക്കാണ് യോഗ്യതയില്ലാത്തത്',
    sourcesTitle: 'സ്രോതസ്സുകളും റഫറൻസുകളും',
    sourceCredit: 'സ്രോതസ്സ്: myScheme, ഭാരത സർക്കാർ',
    viewOnMyScheme: 'myScheme-ൽ കാണുക',
    noDocs: 'ഔദ്യോഗിക പദ്ധതി പേജിൽ രേഖകളൊന്നും നൽകിയിട്ടില്ല.',
    applyModeLabel: 'അപേക്ഷാ രീതി',
    stateScheme: 'സംസ്ഥാന പദ്ധതി',
    benefitLabel: 'സാമ്പത്തിക ആനുകൂല്യം',
    navHome: 'ഹോം',
    navSchemes: 'പദ്ധതികൾ',
    navEligibility: 'യോഗ്യത പരിശോധിക്കുക',
    navAskAI: 'AI-യോട് ചോദിക്കുക',
    brandTagline: 'നിങ്ങളുടെ ഭാഷയിൽ പദ്ധതി സഹായി',
    disclaimer: 'സ്വതന്ത്ര പൗര സഹായി, ഔദ്യോഗിക സർക്കാർ വെബ്സൈറ്റ് അല്ല. എപ്പോഴും ഔദ്യോഗിക പദ്ധതി പോർട്ടലിൽ മാത്രം അപേക്ഷിക്കുക.',
    heroSearchBtn: 'തിരയുക',
    statSchemes: 'പദ്ധതികൾ',
    statCategories: 'വിഭാഗങ്ങൾ',
    statLanguages: 'ഭാഷകൾ',
    homeCtaTitle: 'ഏതൊക്കെ പദ്ധതികൾക്ക് യോഗ്യരാണെന്ന് അറിയില്ലേ?',
    homeCtaDesc: 'ചില ലളിതമായ ചോദ്യങ്ങൾക്ക് ഉത്തരം നൽകി ഏകദേശം 2 മിനിറ്റിനുള്ളിൽ നിങ്ങളുടെ യോഗ്യതാ റിപ്പോർട്ട് നേടുക.',
    homeAskTitle: 'നിങ്ങളുടെ ഭാഷയിൽ ചോദിക്കുക',
    homeAskDesc: '10 ഇന്ത്യൻ ഭാഷകളിൽ ഏതിലും AI സഹായിയോട് ടൈപ്പ് ചെയ്തോ സംസാരിച്ചോ ചോദിക്കുക.',
    viewAllSchemes: 'എല്ലാ പദ്ധതികളും കാണുക',
    viewSchemes: 'പദ്ധതികൾ കാണുക',
    schemesTitle: 'സർക്കാർ പദ്ധതികൾ കണ്ടെത്തുക',
    schemesSubtitle: 'വിഭാഗം, യോഗ്യത, ആനുകൂല്യങ്ങൾ എന്നിവ അനുസരിച്ച് പദ്ധതികൾ തിരയുക.',
    filtersTitle: 'ഫിൽട്ടറുകൾ',
    clearFilters: 'എല്ലാം മായ്ക്കുക',
    filterCategory: 'വിഭാഗം',
    filterGender: 'ലിംഗം',
    filterSocialCategory: 'സാമൂഹിക വിഭാഗം',
    filterOccupation: 'തൊഴിൽ',
    filterAny: 'ഏതും',
    sortBy: 'ക്രമീകരിക്കുക',
    sortRelevance: 'പ്രസക്തി',
    sortBenefit: 'ഏറ്റവും കൂടുതൽ ആനുകൂല്യം',
    sortName: 'പേര് (A–Z)',
    resultsCount: '{count} പദ്ധതികൾ കണ്ടെത്തി',
    noResults: 'നിങ്ങളുടെ തിരയലിന് പൊരുത്തപ്പെടുന്ന പദ്ധതികളില്ല. ചില ഫിൽട്ടറുകൾ നീക്കി നോക്കുക.',
    viewDetails: 'വിശദാംശങ്ങൾ കാണുക',
    backToSchemes: 'പദ്ധതികളിലേക്ക് മടങ്ങുക',
    tabDetails: 'വിശദാംശങ്ങൾ',
    tabBenefits: 'ആനുകൂല്യങ്ങൾ',
    tabEligibility: 'യോഗ്യത',
    tabApply: 'അപേക്ഷാ നടപടി',
    tabDocuments: 'ആവശ്യമായ രേഖകൾ',
    applyOfficial: 'ഔദ്യോഗിക പോർട്ടലിൽ അപേക്ഷിക്കുക',
    checkEligibilityBtn: 'നിങ്ങളുടെ യോഗ്യത പരിശോധിക്കുക',
    listenBtn: 'കേൾക്കുക',
    stopBtn: 'നിർത്തുക',
    askAiAbout: 'ഈ പദ്ധതിയെക്കുറിച്ച് AI-യോട് ചോദിക്കുക',
    ministry: 'മന്ത്രാലയം / വകുപ്പ്',
    schemeLevel: 'പദ്ധതി തലം',
    officialWebsite: 'ഔദ്യോഗിക വെബ്സൈറ്റ്',
    eligibilityIntro: 'ഈ എല്ലാ വ്യവസ്ഥകളും പാലിക്കുന്നുവെങ്കിൽ നിങ്ങൾക്ക് യോഗ്യതയുണ്ടാകാം:',
    eligibilityNone: 'പ്രത്യേക നിയന്ത്രണങ്ങളില്ല. എല്ലാ പൗരന്മാർക്കും.',
    eligibilityCheckCta: 'ഉറപ്പില്ലേ? ചില ചോദ്യങ്ങൾക്ക് ഉത്തരം നൽകി നിങ്ങളുടെ യോഗ്യത പരിശോധിക്കുക.',
    docsIntro: 'നിങ്ങളുടെ കൈവശമുള്ള രേഖകൾ അടയാളപ്പെടുത്തുക, ഇനി എന്താണ് വേണ്ടതെന്ന് അറിയാം.',
    docsReady: '{total} ൽ {ready} രേഖകൾ തയ്യാർ',
    docsAllReady: 'എല്ലാ രേഖകളും തയ്യാർ. ഇപ്പോൾ അപേക്ഷിക്കാം.',
    applyHelp: 'സഹായം വേണോ? ഈ രേഖകളുമായി അടുത്തുള്ള കോമൺ സർവീസ് സെന്ററിൽ (CSC) പോയി അപേക്ഷിക്കുക.',
    quickFacts: 'പ്രധാന വിവരങ്ങൾ',
    notFound: 'പദ്ധതി കണ്ടെത്തിയില്ല.'
  },
  pa: {
    applyOnline: 'ਔਨਲਾਈਨ ਅਰਜ਼ੀ ਦਿਓ (ਅਧਿਕਾਰਤ ਸਾਈਟ)',
    applyPortal: 'ਅਧਿਕਾਰਤ ਪੋਰਟਲ \'ਤੇ ਜਾਓ',
    applyForm: 'ਅਰਜ਼ੀ ਫਾਰਮ ਡਾਊਨਲੋਡ ਕਰੋ',
    applyOfflineTitle: 'ਔਫਲਾਈਨ ਅਰਜ਼ੀ ਦਿਓ',
    applyOfflineNote: 'ਇਸ ਯੋਜਨਾ ਲਈ ਔਨਲਾਈਨ ਅਰਜ਼ੀ ਨਹੀਂ ਹੈ। ਹੇਠਾਂ ਦਿੱਤੇ ਅਧਿਕਾਰਤ ਕਦਮਾਂ ਵਿੱਚ ਦੱਸੇ ਦਫ਼ਤਰ, ਬੈਂਕ ਜਾਂ CSC \'ਤੇ ਅਰਜ਼ੀ ਦਿਓ।',
    howToApply: 'ਅਰਜ਼ੀ ਕਿਵੇਂ ਦੇਣੀ ਹੈ',
    mySchemeInfoOnly: 'ਯੋਜਨਾ ਜਾਣਕਾਰੀ ਪੰਨਾ। ਅਰਜ਼ੀਆਂ ਵਿਭਾਗ ਦੇ ਪੋਰਟਲ ਜਾਂ ਦਫ਼ਤਰ ਵਿੱਚ ਦਿੱਤੀਆਂ ਜਾਂਦੀਆਂ ਹਨ, myScheme \'ਤੇ ਨਹੀਂ।',
    clearChat: 'ਚੈਟ ਸਾਫ਼ ਕਰੋ',
    feedbackTitle: 'ਕੀ ਇਹ ਜਾਣਕਾਰੀ ਲਾਭਦਾਇਕ ਸੀ?',
    feedbackYes: 'ਹਾਂ',
    feedbackNo: 'ਨਹੀਂ',
    feedbackThanks: 'ਤੁਹਾਡੀ ਫੀਡਬੈਕ ਲਈ ਧੰਨਵਾਦ',
    reportWrongInfo: 'ਗਲਤ ਜਾਣਕਾਰੀ ਦੀ ਰਿਪੋਰਟ ਕਰੋ',
    reportPrompt: 'ਇਸ ਪੰਨੇ ਤੇ ਕੀ ਗਲਤ ਜਾਂ ਪੁਰਾਣਾ ਹੈ?',
    reportPlaceholder: 'ਉਦਾਹਰਨ: ਆਮਦਨ ਸੀਮਾ ਬਦਲ ਗਈ ਹੈ, ਜਾਂ ਲਿੰਕ ਕੰਮ ਨਹੀਂ ਕਰਦਾ',
    reportPrivacy: 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਨਾਮ, ਫ਼ੋਨ ਨੰਬਰ, ਆਧਾਰ ਜਾਂ ਹੋਰ ਨਿੱਜੀ ਵੇਰਵੇ ਨਾ ਲਿਖੋ।',
    reportSend: 'ਰਿਪੋਰਟ ਭੇਜੋ',
    reportCancel: 'ਰੱਦ ਕਰੋ',
    reportThanks: 'ਧੰਨਵਾਦ। ਤੁਹਾਡੀ ਰਿਪੋਰਟ ਯੋਜਨਾ ਦੀ ਜਾਣਕਾਰੀ ਸਹੀ ਰੱਖਣ ਵਿੱਚ ਮਦਦ ਕਰਦੀ ਹੈ।',
    feedbackUnavailable: 'ਹੁਣੇ ਫੀਡਬੈਕ ਸੰਭਾਲੀ ਨਹੀਂ ਜਾ ਸਕਦੀ। ਕਿਰਪਾ ਕਰਕੇ ਬਾਅਦ ਵਿੱਚ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
    feedbackError: 'ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
    prevPage: 'ਪਿਛਲਾ',
    nextPage: 'ਅਗਲਾ',
    pageRange: '{total} ਵਿੱਚੋਂ {from}–{to} ਯੋਜਨਾਵਾਂ ਵਿਖਾਈਆਂ ਜਾ ਰਹੀਆਂ ਹਨ',
    pageNav: 'ਯੋਜਨਾ ਪੰਨੇ',
    goToPage: 'ਪੰਨਾ {page} ਤੇ ਜਾਓ',
    showMore: '{count} ਹੋਰ ਯੋਜਨਾਵਾਂ ਵਿਖਾਓ',
    catStudent: 'ਵਿਦਿਆਰਥੀ / ਸਿੱਖਿਆ',
    catAgri: 'ਖੇਤੀਬਾੜੀ / ਕਿਸਾਨ',
    catBiz: 'ਉੱਦਮਤਾ / MSME',
    catWomen: 'ਔਰਤਾਂ / ਪਰਿਵਾਰ ਭਲਾਈ',
    catSocial: 'ਬਜ਼ੁਰਗ ਨਾਗਰਿਕ / ਸਮਾਜ ਭਲਾਈ',
    catSkills: 'ਰੁਜ਼ਗਾਰ / ਹੁਨਰ ਵਿਕਾਸ',
    schemeCount: '{count} ਯੋਜਨਾਵਾਂ',
    categoriesSubtitle: 'ਲਾਭਪਾਤਰੀ ਵਰਗ ਅਨੁਸਾਰ {count} ਕੇਂਦਰ ਅਤੇ ਰਾਜ ਸਰਕਾਰ ਦੀਆਂ ਯੋਜਨਾਵਾਂ ਵੇਖੋ।',
    howItWorksBadge: 'ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ',
    genderFemale: 'ਔਰਤ',
    genderMale: 'ਮਰਦ',
    socialGeneral: 'ਜਨਰਲ',
    occStudent: 'ਵਿਦਿਆਰਥੀ',
    occFarmer: 'ਕਿਸਾਨ',
    occSelfEmployed: 'ਸਵੈ-ਰੁਜ਼ਗਾਰ / MSME',
    occArtisan: 'ਕਾਰੀਗਰ',
    occHomemaker: 'ਘਰੇਲੂ ਔਰਤ',
    occRuralWorker: 'ਪੇਂਡੂ ਮਜ਼ਦੂਰ',
    levelCentral: 'ਕੇਂਦਰ',
    levelState: 'ਰਾਜ',
    lastChecked: 'ਜਾਣਕਾਰੀ ਆਖਰੀ ਵਾਰ ਜਾਂਚੀ ਗਈ',
    footerTagline: 'ਹਰ ਨਾਗਰਿਕ ਨੂੰ ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ ਲੱਭਣ, ਸਮਝਣ ਅਤੇ ਅਰਜ਼ੀ ਦੇਣ ਵਿੱਚ ਮਦਦ।',
    footerDisclaimer: 'GoodBridgeScheme AI ਇੱਕ ਸੁਤੰਤਰ ਸਹਾਇਕ ਹੈ ਅਤੇ ਭਾਰਤ ਸਰਕਾਰ ਨਾਲ ਜੁੜਿਆ ਨਹੀਂ ਹੈ। ਯੋਜਨਾ ਦੀ ਜਾਣਕਾਰੀ ਭਾਰਤ ਸਰਕਾਰ ਦੇ ਅਧਿਕਾਰਤ ਯੋਜਨਾ ਪਲੇਟਫਾਰਮ myScheme (myscheme.gov.in) ਅਤੇ ਅਧਿਕਾਰਤ ਰਾਜ ਪੋਰਟਲਾਂ ਤੋਂ ਲਈ ਗਈ ਹੈ; ਅਰਜ਼ੀ ਦੇਣ ਤੋਂ ਪਹਿਲਾਂ ਹਮੇਸ਼ਾ ਅਧਿਕਾਰਤ ਵੈੱਬਸਾਈਟ ਤੇ ਪੁਸ਼ਟੀ ਕਰੋ।',
    officialPortalLink: 'ਅਧਿਕਾਰਤ myScheme ਪੋਰਟਲ',
    translatedNote: 'ਅਧਿਕਾਰਤ ਅੰਗਰੇਜ਼ੀ ਲਿਖਤ ਤੋਂ AI ਦੁਆਰਾ ਅਨੁਵਾਦ ਕੀਤਾ ਗਿਆ।',
    showOriginal: 'ਮੂਲ (ਅੰਗਰੇਜ਼ੀ) ਵਿਖਾਓ',
    showTranslation: 'ਅਨੁਵਾਦ ਵਿਖਾਓ',
    translating: 'ਅਨੁਵਾਦ ਹੋ ਰਿਹਾ ਹੈ…',
    chipStudents: 'ਵਿਦਿਆਰਥੀਆਂ ਲਈ ਵਜ਼ੀਫ਼ੇ',
    chipFarmers: 'ਕਿਸਾਨਾਂ ਲਈ ਯੋਜਨਾਵਾਂ',
    chipWomen: 'ਔਰਤਾਂ ਲਈ ਯੋਜਨਾਵਾਂ',
    chipPension: 'ਬਜ਼ੁਰਗਾਂ ਲਈ ਪੈਨਸ਼ਨ',
    chipBusiness: 'ਕਾਰੋਬਾਰ ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਕਰਜ਼ਾ',
    chipJobs: 'ਨੌਕਰੀਆਂ ਅਤੇ ਹੁਨਰ ਸਿਖਲਾਈ',
    chipHowApply: '{name} ਲਈ ਅਰਜ਼ੀ ਕਿਵੇਂ ਦੇਣੀ ਹੈ?',
    chipDocs: '{name} ਲਈ ਕਿਹੜੇ ਦਸਤਾਵੇਜ਼ ਚਾਹੀਦੇ ਹਨ?',
    chipEligible: 'ਕੀ ਮੈਂ {name} ਲਈ ਯੋਗ ਹਾਂ?',
    voiceUnavailable: 'ਇਸ ਡਿਵਾਈਸ ਤੇ {lang} ਆਵਾਜ਼ ਉਪਲਬਧ ਨਹੀਂ ਹੈ, ਇਸ ਲਈ ਜਵਾਬ ਟੈਕਸਟ ਵਿੱਚ ਦਿਖਾਏ ਜਾ ਰਹੇ ਹਨ। ਆਵਾਜ਼ ਲਈ Microsoft Edge ਵਰਤੋ ਜਾਂ Windows ਸੈਟਿੰਗਾਂ ਵਿੱਚ ਆਵਾਜ਼ ਜੋੜੋ।',
    micBlocked: 'ਮਾਈਕ੍ਰੋਫ਼ੋਨ ਦੀ ਇਜਾਜ਼ਤ ਬੰਦ ਹੈ। ਇਸ ਸਾਈਟ ਲਈ ਮਾਈਕ੍ਰੋਫ਼ੋਨ ਦੀ ਇਜਾਜ਼ਤ ਦਿਓ ਅਤੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
    micFailed: 'ਤੁਹਾਡੀ ਆਵਾਜ਼ ਸੁਣਾਈ ਨਹੀਂ ਦਿੱਤੀ। ਇੰਟਰਨੈੱਟ ਕਨੈਕਸ਼ਨ ਜਾਂਚੋ ਅਤੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ, ਜਾਂ ਆਪਣਾ ਸਵਾਲ ਲਿਖੋ।',
    heroSubtitleAll: 'AI ਆਵਾਜ਼ ਅਤੇ ਟੈਕਸਟ ਦੀ ਮਦਦ ਨਾਲ {count} ਕੇਂਦਰ ਅਤੇ ਰਾਜ ਸਰਕਾਰ ਦੀਆਂ ਯੋਜਨਾਵਾਂ ਲੱਭੋ, ਤੁਰੰਤ ਯੋਗਤਾ ਜਾਂਚੋ ਅਤੇ ਅਰਜ਼ੀ ਲਈ ਮਾਰਗਦਰਸ਼ਨ ਪ੍ਰਾਪਤ ਕਰੋ।',
    exclusionsTitle: 'ਕੌਣ ਯੋਗ ਨਹੀਂ ਹੈ',
    sourcesTitle: 'ਸਰੋਤ ਅਤੇ ਹਵਾਲੇ',
    sourceCredit: 'ਸਰੋਤ: myScheme, ਭਾਰਤ ਸਰਕਾਰ',
    viewOnMyScheme: 'myScheme ਤੇ ਵੇਖੋ',
    noDocs: 'ਅਧਿਕਾਰਤ ਯੋਜਨਾ ਪੰਨੇ ਤੇ ਕੋਈ ਦਸਤਾਵੇਜ਼ ਸੂਚੀਬੱਧ ਨਹੀਂ ਹਨ।',
    applyModeLabel: 'ਅਰਜ਼ੀ ਦਾ ਤਰੀਕਾ',
    stateScheme: 'ਰਾਜ ਯੋਜਨਾ',
    benefitLabel: 'ਵਿੱਤੀ ਲਾਭ',
    navHome: 'ਮੁੱਖ ਪੰਨਾ',
    navSchemes: 'ਯੋਜਨਾਵਾਂ',
    navEligibility: 'ਯੋਗਤਾ ਜਾਂਚੋ',
    navAskAI: 'AI ਨੂੰ ਪੁੱਛੋ',
    brandTagline: 'ਤੁਹਾਡੀ ਭਾਸ਼ਾ ਵਿੱਚ ਯੋਜਨਾ ਸਹਾਇਕ',
    disclaimer: 'ਸੁਤੰਤਰ ਨਾਗਰਿਕ ਸਹਾਇਕ, ਅਧਿਕਾਰਤ ਸਰਕਾਰੀ ਵੈੱਬਸਾਈਟ ਨਹੀਂ। ਹਮੇਸ਼ਾ ਅਧਿਕਾਰਤ ਯੋਜਨਾ ਪੋਰਟਲ ਤੇ ਹੀ ਅਰਜ਼ੀ ਦਿਓ।',
    heroSearchBtn: 'ਖੋਜੋ',
    statSchemes: 'ਯੋਜਨਾਵਾਂ',
    statCategories: 'ਸ਼੍ਰੇਣੀਆਂ',
    statLanguages: 'ਭਾਸ਼ਾਵਾਂ',
    homeCtaTitle: 'ਪਤਾ ਨਹੀਂ ਕਿਹੜੀਆਂ ਯੋਜਨਾਵਾਂ ਲਈ ਤੁਸੀਂ ਯੋਗ ਹੋ?',
    homeCtaDesc: 'ਕੁਝ ਆਸਾਨ ਸਵਾਲਾਂ ਦੇ ਜਵਾਬ ਦਿਓ ਅਤੇ ਲਗਭਗ 2 ਮਿੰਟਾਂ ਵਿੱਚ ਆਪਣੀ ਯੋਗਤਾ ਰਿਪੋਰਟ ਪ੍ਰਾਪਤ ਕਰੋ।',
    homeAskTitle: 'ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਪੁੱਛੋ',
    homeAskDesc: '10 ਭਾਰਤੀ ਭਾਸ਼ਾਵਾਂ ਵਿੱਚੋਂ ਕਿਸੇ ਵਿੱਚ ਵੀ AI ਸਹਾਇਕ ਨੂੰ ਲਿਖ ਕੇ ਜਾਂ ਬੋਲ ਕੇ ਪੁੱਛੋ।',
    viewAllSchemes: 'ਸਾਰੀਆਂ ਯੋਜਨਾਵਾਂ ਵੇਖੋ',
    viewSchemes: 'ਯੋਜਨਾਵਾਂ ਵੇਖੋ',
    schemesTitle: 'ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ ਲੱਭੋ',
    schemesSubtitle: 'ਸ਼੍ਰੇਣੀ, ਯੋਗਤਾ ਅਤੇ ਲਾਭਾਂ ਅਨੁਸਾਰ ਯੋਜਨਾਵਾਂ ਖੋਜੋ।',
    filtersTitle: 'ਫਿਲਟਰ',
    clearFilters: 'ਸਭ ਹਟਾਓ',
    filterCategory: 'ਸ਼੍ਰੇਣੀ',
    filterGender: 'ਲਿੰਗ',
    filterSocialCategory: 'ਸਮਾਜਿਕ ਵਰਗ',
    filterOccupation: 'ਕਿੱਤਾ',
    filterAny: 'ਕੋਈ ਵੀ',
    sortBy: 'ਕ੍ਰਮ',
    sortRelevance: 'ਪ੍ਰਸੰਗਿਕਤਾ',
    sortBenefit: 'ਸਭ ਤੋਂ ਵੱਧ ਲਾਭ',
    sortName: 'ਨਾਮ (A–Z)',
    resultsCount: '{count} ਯੋਜਨਾਵਾਂ ਮਿਲੀਆਂ',
    noResults: 'ਤੁਹਾਡੀ ਖੋਜ ਨਾਲ ਕੋਈ ਯੋਜਨਾ ਨਹੀਂ ਮਿਲੀ। ਕੁਝ ਫਿਲਟਰ ਹਟਾ ਕੇ ਵੇਖੋ।',
    viewDetails: 'ਵੇਰਵੇ ਵੇਖੋ',
    backToSchemes: 'ਯੋਜਨਾਵਾਂ ਤੇ ਵਾਪਸ',
    tabDetails: 'ਵੇਰਵੇ',
    tabBenefits: 'ਲਾਭ',
    tabEligibility: 'ਯੋਗਤਾ',
    tabApply: 'ਅਰਜ਼ੀ ਪ੍ਰਕਿਰਿਆ',
    tabDocuments: 'ਲੋੜੀਂਦੇ ਦਸਤਾਵੇਜ਼',
    applyOfficial: 'ਅਧਿਕਾਰਤ ਪੋਰਟਲ ਤੇ ਅਰਜ਼ੀ ਦਿਓ',
    checkEligibilityBtn: 'ਆਪਣੀ ਯੋਗਤਾ ਜਾਂਚੋ',
    listenBtn: 'ਸੁਣੋ',
    stopBtn: 'ਰੋਕੋ',
    askAiAbout: 'ਇਸ ਯੋਜਨਾ ਬਾਰੇ AI ਨੂੰ ਪੁੱਛੋ',
    ministry: 'ਮੰਤਰਾਲਾ / ਵਿਭਾਗ',
    schemeLevel: 'ਯੋਜਨਾ ਪੱਧਰ',
    officialWebsite: 'ਅਧਿਕਾਰਤ ਵੈੱਬਸਾਈਟ',
    eligibilityIntro: 'ਜੇ ਤੁਸੀਂ ਇਹ ਸਾਰੀਆਂ ਸ਼ਰਤਾਂ ਪੂਰੀਆਂ ਕਰਦੇ ਹੋ ਤਾਂ ਤੁਸੀਂ ਯੋਗ ਹੋ ਸਕਦੇ ਹੋ:',
    eligibilityNone: 'ਕੋਈ ਖਾਸ ਸ਼ਰਤ ਨਹੀਂ। ਸਾਰੇ ਨਾਗਰਿਕਾਂ ਲਈ।',
    eligibilityCheckCta: 'ਪੱਕਾ ਨਹੀਂ? ਕੁਝ ਸਵਾਲਾਂ ਦੇ ਜਵਾਬ ਦੇ ਕੇ ਆਪਣੀ ਯੋਗਤਾ ਜਾਂਚੋ।',
    docsIntro: 'ਤੁਹਾਡੇ ਕੋਲ ਮੌਜੂਦ ਦਸਤਾਵੇਜ਼ਾਂ ਤੇ ਨਿਸ਼ਾਨ ਲਗਾਓ, ਤਾਂ ਜੋ ਪਤਾ ਲੱਗੇ ਕੀ ਬਾਕੀ ਹੈ।',
    docsReady: '{total} ਵਿੱਚੋਂ {ready} ਦਸਤਾਵੇਜ਼ ਤਿਆਰ',
    docsAllReady: 'ਸਾਰੇ ਦਸਤਾਵੇਜ਼ ਤਿਆਰ ਹਨ। ਹੁਣ ਤੁਸੀਂ ਅਰਜ਼ੀ ਦੇ ਸਕਦੇ ਹੋ।',
    applyHelp: 'ਮਦਦ ਚਾਹੀਦੀ ਹੈ? ਇਹਨਾਂ ਦਸਤਾਵੇਜ਼ਾਂ ਨਾਲ ਨੇੜਲੇ ਕਾਮਨ ਸਰਵਿਸ ਸੈਂਟਰ (CSC) ਤੇ ਜਾ ਕੇ ਅਰਜ਼ੀ ਦਿਓ।',
    quickFacts: 'ਮੁੱਖ ਜਾਣਕਾਰੀ',
    notFound: 'ਯੋਜਨਾ ਨਹੀਂ ਮਿਲੀ।'
  }
};
