/**
 * UI strings for site navigation, the schemes search page and the scheme detail page.
 * Kept separate from vernacularDictionary.ts; getTranslation() checks both.
 * Keys missing in a language fall back to English. Use {name} placeholders for values.
 */
export const SITE_STRINGS: Record<string, Record<string, string>> = {
  en: {
    voiceUnavailable: 'No {lang} voice is installed on this device, so answers are shown as text. For voice, try Microsoft Edge or add the voice in Windows Settings.',
    micBlocked: 'Microphone access is blocked. Allow the microphone for this site and try again.',
    micFailed: 'Could not hear you. Check your internet connection and try again, or type your question.',
    exclusionsTitle: 'Who is not eligible',
    sourcesTitle: 'Sources & references',
    sourceCredit: 'Source: myScheme, Government of India',
    viewOnMyScheme: 'View on myScheme',
    noDocs: 'No documents are listed on the official scheme page.',
    applyModeLabel: 'Mode of application',
    stateScheme: 'State scheme',
    benefitLabel: 'Financial Benefit',
    navHome: 'Home',
    navSchemes: 'Schemes',
    navEligibility: 'Check Eligibility',
    navAskAI: 'Ask AI',
    brandTagline: 'Vernacular Scheme Assistant',
    disclaimer: 'Independent citizen assistant, not an official government website. Always apply on the official scheme portal.',
    heroSearchBtn: 'Search',
    statSchemes: 'Schemes',
    statCategories: 'Categories',
    statLanguages: 'Languages',
    homeCtaTitle: 'Not sure which schemes you qualify for?',
    homeCtaDesc: 'Answer a few simple questions and get a personalised eligibility report in about 2 minutes.',
    homeAskTitle: 'Ask in your own language',
    homeAskDesc: 'Type or speak your question to the AI assistant in any of 10 Indian languages.',
    viewAllSchemes: 'View all schemes',
    viewSchemes: 'View schemes',
    schemesTitle: 'Explore Government Schemes',
    schemesSubtitle: 'Search and filter schemes by category, eligibility and benefits.',
    filtersTitle: 'Filters',
    clearFilters: 'Clear all',
    filterCategory: 'Category',
    filterGender: 'Gender',
    filterSocialCategory: 'Social Category',
    filterOccupation: 'Occupation',
    filterAny: 'Any',
    sortBy: 'Sort by',
    sortRelevance: 'Relevance',
    sortBenefit: 'Highest benefit',
    sortName: 'Name (A–Z)',
    resultsCount: '{count} schemes found',
    noResults: 'No schemes match your search. Try removing some filters.',
    viewDetails: 'View details',
    backToSchemes: 'Back to schemes',
    tabDetails: 'Details',
    tabBenefits: 'Benefits',
    tabEligibility: 'Eligibility',
    tabApply: 'Application Process',
    tabDocuments: 'Documents Required',
    applyOfficial: 'Apply on Official Portal',
    checkEligibilityBtn: 'Check Your Eligibility',
    listenBtn: 'Listen',
    stopBtn: 'Stop',
    askAiAbout: 'Ask AI about this scheme',
    ministry: 'Ministry / Department',
    schemeLevel: 'Scheme level',
    lastChecked: 'Information last checked',
    officialWebsite: 'Official website',
    eligibilityIntro: 'You may be eligible if you meet all of these conditions:',
    eligibilityNone: 'No specific restrictions. Open to all citizens.',
    eligibilityCheckCta: 'Not sure? Answer a few questions to check if you qualify.',
    docsIntro: 'Tick the documents you already have to see what is still missing.',
    docsReady: '{ready} of {total} documents ready',
    docsAllReady: 'All documents ready. You can apply now.',
    applyHelp: 'Need help? Visit your nearest Common Service Centre (CSC) to apply in person with these documents.',
    quickFacts: 'Quick facts',
    notFound: 'Scheme not found.',
    heroSubtitleAll: 'Discover, check instant eligibility, and get guided application help for {count} central and state government schemes, using AI voice and text.',
    footerTagline: 'Helping every citizen discover, understand and apply for government schemes in their own language.',
    footerDisclaimer: 'GoodBridgeScheme AI is an independent assistant and is not affiliated with the Government of India. Scheme information is reproduced from myScheme (myscheme.gov.in), the Government of India’s official scheme platform, and official state portals; always confirm details on the official website before applying.'
  },
  hi: {
    voiceUnavailable: 'इस डिवाइस पर {lang} आवाज़ उपलब्ध नहीं है, इसलिए उत्तर टेक्स्ट में दिखाए जा रहे हैं। आवाज़ के लिए Microsoft Edge आज़माएं या Windows सेटिंग्स में आवाज़ जोड़ें।',
    micBlocked: 'माइक्रोफ़ोन की अनुमति बंद है। इस साइट के लिए माइक्रोफ़ोन की अनुमति दें और फिर कोशिश करें।',
    micFailed: 'आपकी आवाज़ सुनाई नहीं दी। इंटरनेट कनेक्शन जाँचें और फिर कोशिश करें, या अपना सवाल लिखें।',
    heroSubtitleAll: 'AI आवाज़ और टेक्स्ट की मदद से {count} केंद्र और राज्य सरकार की योजनाएं खोजें, तुरंत पात्रता जाँचें और आवेदन में मार्गदर्शन पाएं।',
    exclusionsTitle: 'कौन पात्र नहीं है',
    sourcesTitle: 'स्रोत और संदर्भ',
    sourceCredit: 'स्रोत: myScheme, भारत सरकार',
    viewOnMyScheme: 'myScheme पर देखें',
    noDocs: 'आधिकारिक योजना पृष्ठ पर कोई दस्तावेज़ सूचीबद्ध नहीं है।',
    applyModeLabel: 'आवेदन का तरीका',
    stateScheme: 'राज्य योजना',
    benefitLabel: 'आर्थिक लाभ',
    navHome: 'होम',
    navSchemes: 'योजनाएं',
    navEligibility: 'पात्रता जाँचें',
    navAskAI: 'AI से पूछें',
    brandTagline: 'आपकी भाषा में योजना सहायक',
    disclaimer: 'स्वतंत्र नागरिक सहायक, आधिकारिक सरकारी वेबसाइट नहीं। हमेशा आधिकारिक योजना पोर्टल पर ही आवेदन करें।',
    heroSearchBtn: 'खोजें',
    statSchemes: 'योजनाएं',
    statCategories: 'श्रेणियां',
    statLanguages: 'भाषाएं',
    homeCtaTitle: 'पता नहीं किन योजनाओं के लिए आप पात्र हैं?',
    homeCtaDesc: 'कुछ आसान सवालों के जवाब दें और लगभग 2 मिनट में अपनी पात्रता रिपोर्ट पाएं।',
    homeAskTitle: 'अपनी भाषा में पूछें',
    homeAskDesc: '10 भारतीय भाषाओं में से किसी में भी AI सहायक से लिखकर या बोलकर पूछें।',
    viewAllSchemes: 'सभी योजनाएं देखें',
    viewSchemes: 'योजनाएं देखें',
    schemesTitle: 'सरकारी योजनाएं खोजें',
    schemesSubtitle: 'श्रेणी, पात्रता और लाभ के अनुसार योजनाएं खोजें और छाँटें।',
    filtersTitle: 'फ़िल्टर',
    clearFilters: 'सभी हटाएं',
    filterCategory: 'श्रेणी',
    filterGender: 'लिंग',
    filterSocialCategory: 'सामाजिक वर्ग',
    filterOccupation: 'व्यवसाय',
    filterAny: 'कोई भी',
    sortBy: 'क्रम',
    sortRelevance: 'प्रासंगिकता',
    sortBenefit: 'सबसे अधिक लाभ',
    sortName: 'नाम (A–Z)',
    resultsCount: '{count} योजनाएं मिलीं',
    noResults: 'आपकी खोज से कोई योजना नहीं मिली। कुछ फ़िल्टर हटाकर देखें।',
    viewDetails: 'विवरण देखें',
    backToSchemes: 'योजनाओं पर वापस',
    tabDetails: 'विवरण',
    tabBenefits: 'लाभ',
    tabEligibility: 'पात्रता',
    tabApply: 'आवेदन प्रक्रिया',
    tabDocuments: 'आवश्यक दस्तावेज़',
    applyOfficial: 'आधिकारिक पोर्टल पर आवेदन करें',
    checkEligibilityBtn: 'अपनी पात्रता जाँचें',
    listenBtn: 'सुनें',
    stopBtn: 'रोकें',
    askAiAbout: 'इस योजना के बारे में AI से पूछें',
    ministry: 'मंत्रालय / विभाग',
    schemeLevel: 'योजना स्तर',
    officialWebsite: 'आधिकारिक वेबसाइट',
    eligibilityIntro: 'यदि आप ये सभी शर्तें पूरी करते हैं तो आप पात्र हो सकते हैं:',
    eligibilityNone: 'कोई विशेष शर्त नहीं। सभी नागरिकों के लिए।',
    eligibilityCheckCta: 'पक्का नहीं? कुछ सवालों के जवाब देकर अपनी पात्रता जाँचें।',
    docsIntro: 'जो दस्तावेज़ आपके पास हैं उन पर निशान लगाएं, ताकि पता चले क्या बाकी है।',
    docsReady: '{total} में से {ready} दस्तावेज़ तैयार',
    docsAllReady: 'सभी दस्तावेज़ तैयार हैं। अब आप आवेदन कर सकते हैं।',
    applyHelp: 'मदद चाहिए? इन दस्तावेज़ों के साथ अपने नज़दीकी जन सेवा केंद्र (CSC) पर जाकर आवेदन करें।',
    quickFacts: 'मुख्य जानकारी',
    notFound: 'योजना नहीं मिली।'
  },
  ta: {
    voiceUnavailable: 'இந்தச் சாதனத்தில் {lang} குரல் இல்லை, எனவே பதில்கள் உரையாகக் காட்டப்படுகின்றன. குரலுக்கு Microsoft Edge-ஐ முயற்சிக்கவும் அல்லது Windows அமைப்புகளில் குரலைச் சேர்க்கவும்.',
    micBlocked: 'மைக்ரோஃபோன் அனுமதி தடுக்கப்பட்டுள்ளது. இந்தத் தளத்திற்கு மைக்ரோஃபோனை அனுமதித்து மீண்டும் முயற்சிக்கவும்.',
    micFailed: 'உங்கள் குரல் கேட்கவில்லை. இணைய இணைப்பைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும், அல்லது உங்கள் கேள்வியைத் தட்டச்சு செய்யவும்.',
    heroSubtitleAll: 'AI குரல் மற்றும் உரை மூலம் {count} மத்திய மற்றும் மாநில அரசுத் திட்டங்களைக் கண்டறியுங்கள், உடனடியாகத் தகுதியைச் சரிபார்த்து, விண்ணப்ப வழிகாட்டுதலைப் பெறுங்கள்.',
    exclusionsTitle: 'யார் தகுதியற்றவர்கள்',
    sourcesTitle: 'ஆதாரங்கள் மற்றும் குறிப்புகள்',
    sourceCredit: 'ஆதாரம்: myScheme, இந்திய அரசு',
    viewOnMyScheme: 'myScheme-இல் காண்க',
    noDocs: 'அதிகாரப்பூர்வ திட்டப் பக்கத்தில் ஆவணங்கள் குறிப்பிடப்படவில்லை.',
    applyModeLabel: 'விண்ணப்ப முறை',
    stateScheme: 'மாநிலத் திட்டம்',
    benefitLabel: 'நிதி பலன்',
    navHome: 'முகப்பு',
    navSchemes: 'திட்டங்கள்',
    navEligibility: 'தகுதி சரிபார்',
    navAskAI: 'AI-யிடம் கேளுங்கள்',
    brandTagline: 'உங்கள் மொழியில் திட்ட உதவியாளர்',
    disclaimer: 'சுயாதீன குடிமக்கள் உதவியாளர், அதிகாரப்பூர்வ அரசு இணையதளம் அல்ல. எப்போதும் அதிகாரப்பூர்வ திட்ட இணையதளத்தில் விண்ணப்பிக்கவும்.',
    heroSearchBtn: 'தேடு',
    statSchemes: 'திட்டங்கள்',
    statCategories: 'வகைகள்',
    statLanguages: 'மொழிகள்',
    homeCtaTitle: 'எந்தத் திட்டங்களுக்குத் தகுதியானவர் என்று தெரியவில்லையா?',
    homeCtaDesc: 'சில எளிய கேள்விகளுக்குப் பதிலளித்து சுமார் 2 நிமிடங்களில் உங்கள் தகுதி அறிக்கையைப் பெறுங்கள்.',
    homeAskTitle: 'உங்கள் மொழியில் கேளுங்கள்',
    homeAskDesc: '10 இந்திய மொழிகளில் எதிலும் AI உதவியாளரிடம் தட்டச்சு செய்து அல்லது பேசிக் கேளுங்கள்.',
    viewAllSchemes: 'அனைத்து திட்டங்களையும் காண்க',
    viewSchemes: 'திட்டங்களைக் காண்க',
    schemesTitle: 'அரசுத் திட்டங்களை ஆராயுங்கள்',
    schemesSubtitle: 'வகை, தகுதி மற்றும் பலன்களின் அடிப்படையில் திட்டங்களைத் தேடி வடிகட்டுங்கள்.',
    filtersTitle: 'வடிப்பான்கள்',
    clearFilters: 'அனைத்தையும் நீக்கு',
    filterCategory: 'வகை',
    filterGender: 'பாலினம்',
    filterSocialCategory: 'சமூகப் பிரிவு',
    filterOccupation: 'தொழில்',
    filterAny: 'ஏதேனும்',
    sortBy: 'வரிசைப்படுத்து',
    sortRelevance: 'பொருத்தம்',
    sortBenefit: 'அதிக பலன்',
    sortName: 'பெயர் (A–Z)',
    resultsCount: '{count} திட்டங்கள் கிடைத்தன',
    noResults: 'உங்கள் தேடலுக்குப் பொருந்தும் திட்டங்கள் இல்லை. சில வடிப்பான்களை நீக்கிப் பாருங்கள்.',
    viewDetails: 'விவரங்களைக் காண்க',
    backToSchemes: 'திட்டங்களுக்குத் திரும்பு',
    tabDetails: 'விவரங்கள்',
    tabBenefits: 'பலன்கள்',
    tabEligibility: 'தகுதி',
    tabApply: 'விண்ணப்ப முறை',
    tabDocuments: 'தேவையான ஆவணங்கள்',
    applyOfficial: 'அதிகாரப்பூர்வ இணையதளத்தில் விண்ணப்பிக்கவும்',
    checkEligibilityBtn: 'உங்கள் தகுதியைச் சரிபாருங்கள்',
    listenBtn: 'கேளுங்கள்',
    stopBtn: 'நிறுத்து',
    askAiAbout: 'இந்தத் திட்டம் பற்றி AI-யிடம் கேளுங்கள்',
    ministry: 'அமைச்சகம் / துறை',
    schemeLevel: 'திட்ட நிலை',
    officialWebsite: 'அதிகாரப்பூர்வ இணையதளம்',
    eligibilityIntro: 'இந்த நிபந்தனைகள் அனைத்தையும் பூர்த்தி செய்தால் நீங்கள் தகுதியானவராக இருக்கலாம்:',
    eligibilityNone: 'குறிப்பிட்ட கட்டுப்பாடுகள் இல்லை. அனைத்து குடிமக்களுக்கும்.',
    eligibilityCheckCta: 'உறுதியாகத் தெரியவில்லையா? சில கேள்விகளுக்குப் பதிலளித்து உங்கள் தகுதியைச் சரிபாருங்கள்.',
    docsIntro: 'உங்களிடம் உள்ள ஆவணங்களைக் குறியிடுங்கள், இன்னும் தேவையானவை தெரியும்.',
    docsReady: '{total} இல் {ready} ஆவணங்கள் தயார்',
    docsAllReady: 'அனைத்து ஆவணங்களும் தயார். இப்போது விண்ணப்பிக்கலாம்.',
    applyHelp: 'உதவி தேவையா? இந்த ஆவணங்களுடன் அருகிலுள்ள பொது சேவை மையத்திற்கு (CSC) சென்று விண்ணப்பிக்கலாம்.',
    quickFacts: 'முக்கிய தகவல்கள்',
    notFound: 'திட்டம் கிடைக்கவில்லை.'
  },
  te: {
    voiceUnavailable: 'ఈ పరికరంలో {lang} వాయిస్ లేదు, కాబట్టి సమాధానాలు టెక్స్ట్‌గా చూపబడుతున్నాయి. వాయిస్ కోసం Microsoft Edge ప్రయత్నించండి లేదా Windows సెట్టింగ్స్‌లో వాయిస్ జోడించండి.',
    micBlocked: 'మైక్రోఫోన్ అనుమతి నిరోధించబడింది. ఈ సైట్‌కు మైక్రోఫోన్‌ను అనుమతించి మళ్లీ ప్రయత్నించండి.',
    micFailed: 'మీ మాట వినబడలేదు. ఇంటర్నెట్ కనెక్షన్ తనిఖీ చేసి మళ్లీ ప్రయత్నించండి, లేదా మీ ప్రశ్నను టైప్ చేయండి.',
    heroSubtitleAll: 'AI వాయిస్ మరియు టెక్స్ట్ ద్వారా {count} కేంద్ర మరియు రాష్ట్ర ప్రభుత్వ పథకాలను కనుగొనండి, వెంటనే అర్హతను తనిఖీ చేసి, దరఖాస్తు మార్గదర్శకత్వం పొందండి.',
    exclusionsTitle: 'ఎవరు అర్హులు కారు',
    sourcesTitle: 'మూలాలు & సూచనలు',
    sourceCredit: 'మూలం: myScheme, భారత ప్రభుత్వం',
    viewOnMyScheme: 'mySchemeలో చూడండి',
    noDocs: 'అధికారిక పథకం పేజీలో పత్రాలు ఏవీ ఇవ్వలేదు.',
    applyModeLabel: 'దరఖాస్తు విధానం',
    stateScheme: 'రాష్ట్ర పథకం',
    benefitLabel: 'ఆర్థిక ప్రయోజనం',
    navHome: 'హోమ్',
    navSchemes: 'పథకాలు',
    navEligibility: 'అర్హత తనిఖీ',
    navAskAI: 'AIని అడగండి',
    brandTagline: 'మీ భాషలో పథకాల సహాయకుడు',
    disclaimer: 'స్వతంత్ర పౌర సహాయకుడు, అధికారిక ప్రభుత్వ వెబ్‌సైట్ కాదు. ఎల్లప్పుడూ అధికారిక పథకం పోర్టల్‌లోనే దరఖాస్తు చేయండి.',
    heroSearchBtn: 'వెతకండి',
    statSchemes: 'పథకాలు',
    statCategories: 'వర్గాలు',
    statLanguages: 'భాషలు',
    homeCtaTitle: 'మీరు ఏ పథకాలకు అర్హులో తెలియదా?',
    homeCtaDesc: 'కొన్ని సులభమైన ప్రశ్నలకు సమాధానం ఇచ్చి సుమారు 2 నిమిషాల్లో మీ అర్హత నివేదికను పొందండి.',
    homeAskTitle: 'మీ భాషలోనే అడగండి',
    homeAskDesc: '10 భారతీయ భాషలలో దేనిలోనైనా AI సహాయకుడిని టైప్ చేసి లేదా మాట్లాడి అడగండి.',
    viewAllSchemes: 'అన్ని పథకాలు చూడండి',
    viewSchemes: 'పథకాలు చూడండి',
    schemesTitle: 'ప్రభుత్వ పథకాలను అన్వేషించండి',
    schemesSubtitle: 'వర్గం, అర్హత మరియు ప్రయోజనాల ఆధారంగా పథకాలను వెతకండి.',
    filtersTitle: 'ఫిల్టర్లు',
    clearFilters: 'అన్నీ తొలగించు',
    filterCategory: 'వర్గం',
    filterGender: 'లింగం',
    filterSocialCategory: 'సామాజిక వర్గం',
    filterOccupation: 'వృత్తి',
    filterAny: 'ఏదైనా',
    sortBy: 'క్రమం',
    sortRelevance: 'సంబంధితం',
    sortBenefit: 'అధిక ప్రయోజనం',
    sortName: 'పేరు (A–Z)',
    resultsCount: '{count} పథకాలు దొరికాయి',
    noResults: 'మీ శోధనకు సరిపోయే పథకాలు లేవు. కొన్ని ఫిల్టర్లు తొలగించి చూడండి.',
    viewDetails: 'వివరాలు చూడండి',
    backToSchemes: 'పథకాలకు తిరిగి',
    tabDetails: 'వివరాలు',
    tabBenefits: 'ప్రయోజనాలు',
    tabEligibility: 'అర్హత',
    tabApply: 'దరఖాస్తు విధానం',
    tabDocuments: 'అవసరమైన పత్రాలు',
    applyOfficial: 'అధికారిక పోర్టల్‌లో దరఖాస్తు చేయండి',
    checkEligibilityBtn: 'మీ అర్హతను తనిఖీ చేయండి',
    listenBtn: 'వినండి',
    stopBtn: 'ఆపండి',
    askAiAbout: 'ఈ పథకం గురించి AIని అడగండి',
    ministry: 'మంత్రిత్వ శాఖ / విభాగం',
    schemeLevel: 'పథకం స్థాయి',
    officialWebsite: 'అధికారిక వెబ్‌సైట్',
    eligibilityIntro: 'మీరు ఈ షరతులన్నీ నెరవేరిస్తే అర్హులు కావచ్చు:',
    eligibilityNone: 'ప్రత్యేక పరిమితులు లేవు. పౌరులందరికీ.',
    eligibilityCheckCta: 'ఖచ్చితంగా తెలియదా? కొన్ని ప్రశ్నలకు సమాధానం ఇచ్చి మీ అర్హతను తనిఖీ చేయండి.',
    docsIntro: 'మీ వద్ద ఉన్న పత్రాలను గుర్తించండి, ఇంకా ఏవి కావాలో తెలుస్తుంది.',
    docsReady: '{total}లో {ready} పత్రాలు సిద్ధం',
    docsAllReady: 'అన్ని పత్రాలు సిద్ధం. ఇప్పుడు దరఖాస్తు చేయవచ్చు.',
    applyHelp: 'సహాయం కావాలా? ఈ పత్రాలతో మీ సమీప కామన్ సర్వీస్ సెంటర్ (CSC)కి వెళ్లి దరఖాస్తు చేయండి.',
    quickFacts: 'ముఖ్య సమాచారం',
    notFound: 'పథకం కనబడలేదు.'
  },
  mr: {
    voiceUnavailable: 'या डिव्हाइसवर {lang} आवाज उपलब्ध नाही, त्यामुळे उत्तरे मजकुरात दाखवली जात आहेत. आवाजासाठी Microsoft Edge वापरून पहा किंवा Windows सेटिंग्जमध्ये आवाज जोडा.',
    micBlocked: 'मायक्रोफोनची परवानगी बंद आहे. या साइटसाठी मायक्रोफोनला परवानगी द्या आणि पुन्हा प्रयत्न करा.',
    micFailed: 'तुमचा आवाज ऐकू आला नाही. इंटरनेट कनेक्शन तपासा आणि पुन्हा प्रयत्न करा, किंवा तुमचा प्रश्न लिहा.',
    heroSubtitleAll: 'AI आवाज आणि मजकुराच्या मदतीने {count} केंद्र आणि राज्य सरकारच्या योजना शोधा, त्वरित पात्रता तपासा आणि अर्जासाठी मार्गदर्शन मिळवा.',
    exclusionsTitle: 'कोण पात्र नाही',
    sourcesTitle: 'स्रोत आणि संदर्भ',
    sourceCredit: 'स्रोत: myScheme, भारत सरकार',
    viewOnMyScheme: 'myScheme वर पहा',
    noDocs: 'अधिकृत योजना पृष्ठावर कोणतीही कागदपत्रे दिलेली नाहीत.',
    applyModeLabel: 'अर्जाची पद्धत',
    stateScheme: 'राज्य योजना',
    benefitLabel: 'आर्थिक लाभ',
    navHome: 'मुख्यपृष्ठ',
    navSchemes: 'योजना',
    navEligibility: 'पात्रता तपासा',
    navAskAI: 'AI ला विचारा',
    brandTagline: 'तुमच्या भाषेत योजना सहाय्यक',
    disclaimer: 'स्वतंत्र नागरिक सहाय्यक, अधिकृत सरकारी वेबसाइट नाही. नेहमी अधिकृत योजना पोर्टलवरच अर्ज करा.',
    heroSearchBtn: 'शोधा',
    statSchemes: 'योजना',
    statCategories: 'श्रेणी',
    statLanguages: 'भाषा',
    homeCtaTitle: 'कोणत्या योजनांसाठी पात्र आहात हे माहीत नाही?',
    homeCtaDesc: 'काही सोप्या प्रश्नांची उत्तरे द्या आणि सुमारे 2 मिनिटांत तुमचा पात्रता अहवाल मिळवा.',
    homeAskTitle: 'तुमच्या भाषेत विचारा',
    homeAskDesc: '10 भारतीय भाषांपैकी कोणत्याही भाषेत AI सहाय्यकाला लिहून किंवा बोलून विचारा.',
    viewAllSchemes: 'सर्व योजना पहा',
    viewSchemes: 'योजना पहा',
    schemesTitle: 'सरकारी योजना शोधा',
    schemesSubtitle: 'श्रेणी, पात्रता आणि लाभांनुसार योजना शोधा आणि निवडा.',
    filtersTitle: 'फिल्टर',
    clearFilters: 'सर्व काढा',
    filterCategory: 'श्रेणी',
    filterGender: 'लिंग',
    filterSocialCategory: 'सामाजिक प्रवर्ग',
    filterOccupation: 'व्यवसाय',
    filterAny: 'कोणतेही',
    sortBy: 'क्रम',
    sortRelevance: 'संबंधितता',
    sortBenefit: 'सर्वाधिक लाभ',
    sortName: 'नाव (A–Z)',
    resultsCount: '{count} योजना सापडल्या',
    noResults: 'तुमच्या शोधाशी जुळणारी योजना नाही. काही फिल्टर काढून पहा.',
    viewDetails: 'तपशील पहा',
    backToSchemes: 'योजनांकडे परत',
    tabDetails: 'तपशील',
    tabBenefits: 'लाभ',
    tabEligibility: 'पात्रता',
    tabApply: 'अर्ज प्रक्रिया',
    tabDocuments: 'आवश्यक कागदपत्रे',
    applyOfficial: 'अधिकृत पोर्टलवर अर्ज करा',
    checkEligibilityBtn: 'तुमची पात्रता तपासा',
    listenBtn: 'ऐका',
    stopBtn: 'थांबवा',
    askAiAbout: 'या योजनेबद्दल AI ला विचारा',
    ministry: 'मंत्रालय / विभाग',
    schemeLevel: 'योजनेची पातळी',
    officialWebsite: 'अधिकृत वेबसाइट',
    eligibilityIntro: 'तुम्ही या सर्व अटी पूर्ण करत असल्यास पात्र असू शकता:',
    eligibilityNone: 'कोणतीही विशेष अट नाही. सर्व नागरिकांसाठी.',
    eligibilityCheckCta: 'खात्री नाही? काही प्रश्नांची उत्तरे देऊन तुमची पात्रता तपासा.',
    docsIntro: 'तुमच्याकडे असलेल्या कागदपत्रांवर खूण करा, म्हणजे काय बाकी आहे ते कळेल.',
    docsReady: '{total} पैकी {ready} कागदपत्रे तयार',
    docsAllReady: 'सर्व कागदपत्रे तयार आहेत. आता अर्ज करू शकता.',
    applyHelp: 'मदत हवी आहे? ही कागदपत्रे घेऊन जवळच्या आपले सरकार सेवा केंद्रात (CSC) जाऊन अर्ज करा.',
    quickFacts: 'मुख्य माहिती',
    notFound: 'योजना सापडली नाही.'
  },
  bn: {
    voiceUnavailable: 'এই ডিভাইসে {lang} ভয়েস নেই, তাই উত্তর লেখা আকারে দেখানো হচ্ছে। ভয়েসের জন্য Microsoft Edge ব্যবহার করুন বা Windows সেটিংসে ভয়েস যোগ করুন।',
    micBlocked: 'মাইক্রোফোনের অনুমতি বন্ধ আছে। এই সাইটের জন্য মাইক্রোফোনের অনুমতি দিন এবং আবার চেষ্টা করুন।',
    micFailed: 'আপনার কথা শোনা যায়নি। ইন্টারনেট সংযোগ দেখে আবার চেষ্টা করুন, বা আপনার প্রশ্ন লিখুন।',
    heroSubtitleAll: 'AI ভয়েস ও টেক্সটের মাধ্যমে {count}টি কেন্দ্র ও রাজ্য সরকারের প্রকল্প খুঁজুন, সঙ্গে সঙ্গে যোগ্যতা যাচাই করুন এবং আবেদনের নির্দেশনা পান।',
    exclusionsTitle: 'কারা যোগ্য নন',
    sourcesTitle: 'উৎস ও তথ্যসূত্র',
    sourceCredit: 'উৎস: myScheme, ভারত সরকার',
    viewOnMyScheme: 'myScheme-এ দেখুন',
    noDocs: 'সরকারি প্রকল্প পৃষ্ঠায় কোনো নথি উল্লেখ নেই।',
    applyModeLabel: 'আবেদনের পদ্ধতি',
    stateScheme: 'রাজ্য প্রকল্প',
    benefitLabel: 'আর্থিক সুবিধা',
    navHome: 'হোম',
    navSchemes: 'প্রকল্প',
    navEligibility: 'যোগ্যতা যাচাই',
    navAskAI: 'AI-কে জিজ্ঞাসা করুন',
    brandTagline: 'আপনার ভাষায় প্রকল্প সহায়ক',
    disclaimer: 'স্বাধীন নাগরিক সহায়ক, সরকারি ওয়েবসাইট নয়। সর্বদা সরকারি প্রকল্প পোর্টালেই আবেদন করুন।',
    heroSearchBtn: 'খুঁজুন',
    statSchemes: 'প্রকল্প',
    statCategories: 'বিভাগ',
    statLanguages: 'ভাষা',
    homeCtaTitle: 'কোন প্রকল্পের জন্য যোগ্য তা জানেন না?',
    homeCtaDesc: 'কয়েকটি সহজ প্রশ্নের উত্তর দিন এবং প্রায় 2 মিনিটে আপনার যোগ্যতা রিপোর্ট পান।',
    homeAskTitle: 'নিজের ভাষায় জিজ্ঞাসা করুন',
    homeAskDesc: '10টি ভারতীয় ভাষার যেকোনোটিতে লিখে বা বলে AI সহায়ককে জিজ্ঞাসা করুন।',
    viewAllSchemes: 'সব প্রকল্প দেখুন',
    viewSchemes: 'প্রকল্প দেখুন',
    schemesTitle: 'সরকারি প্রকল্প খুঁজুন',
    schemesSubtitle: 'বিভাগ, যোগ্যতা ও সুবিধা অনুযায়ী প্রকল্প খুঁজুন ও বাছাই করুন।',
    filtersTitle: 'ফিল্টার',
    clearFilters: 'সব মুছুন',
    filterCategory: 'বিভাগ',
    filterGender: 'লিঙ্গ',
    filterSocialCategory: 'সামাজিক শ্রেণি',
    filterOccupation: 'পেশা',
    filterAny: 'যেকোনো',
    sortBy: 'সাজান',
    sortRelevance: 'প্রাসঙ্গিকতা',
    sortBenefit: 'সর্বোচ্চ সুবিধা',
    sortName: 'নাম (A–Z)',
    resultsCount: '{count}টি প্রকল্প পাওয়া গেছে',
    noResults: 'আপনার অনুসন্ধানে কোনো প্রকল্প মেলেনি। কিছু ফিল্টার সরিয়ে দেখুন।',
    viewDetails: 'বিস্তারিত দেখুন',
    backToSchemes: 'প্রকল্পে ফিরে যান',
    tabDetails: 'বিস্তারিত',
    tabBenefits: 'সুবিধা',
    tabEligibility: 'যোগ্যতা',
    tabApply: 'আবেদন প্রক্রিয়া',
    tabDocuments: 'প্রয়োজনীয় নথি',
    applyOfficial: 'সরকারি পোর্টালে আবেদন করুন',
    checkEligibilityBtn: 'আপনার যোগ্যতা যাচাই করুন',
    listenBtn: 'শুনুন',
    stopBtn: 'থামান',
    askAiAbout: 'এই প্রকল্প সম্পর্কে AI-কে জিজ্ঞাসা করুন',
    ministry: 'মন্ত্রক / বিভাগ',
    schemeLevel: 'প্রকল্পের স্তর',
    officialWebsite: 'সরকারি ওয়েবসাইট',
    eligibilityIntro: 'এই সব শর্ত পূরণ করলে আপনি যোগ্য হতে পারেন:',
    eligibilityNone: 'কোনো বিশেষ শর্ত নেই। সব নাগরিকের জন্য।',
    eligibilityCheckCta: 'নিশ্চিত নন? কয়েকটি প্রশ্নের উত্তর দিয়ে আপনার যোগ্যতা যাচাই করুন।',
    docsIntro: 'আপনার কাছে থাকা নথিগুলিতে টিক দিন, কী বাকি আছে তা জানতে পারবেন।',
    docsReady: '{total}টির মধ্যে {ready}টি নথি প্রস্তুত',
    docsAllReady: 'সব নথি প্রস্তুত। এখন আবেদন করতে পারেন।',
    applyHelp: 'সাহায্য দরকার? এই নথিগুলি নিয়ে নিকটতম কমন সার্ভিস সেন্টারে (CSC) গিয়ে আবেদন করুন।',
    quickFacts: 'মূল তথ্য',
    notFound: 'প্রকল্প পাওয়া যায়নি।'
  },
  kn: {
    voiceUnavailable: 'ಈ ಸಾಧನದಲ್ಲಿ {lang} ಧ್ವನಿ ಇಲ್ಲ, ಆದ್ದರಿಂದ ಉತ್ತರಗಳನ್ನು ಪಠ್ಯವಾಗಿ ತೋರಿಸಲಾಗುತ್ತಿದೆ. ಧ್ವನಿಗಾಗಿ Microsoft Edge ಬಳಸಿ ಅಥವಾ Windows ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ ಧ್ವನಿಯನ್ನು ಸೇರಿಸಿ.',
    micBlocked: 'ಮೈಕ್ರೊಫೋನ್ ಅನುಮತಿ ನಿರ್ಬಂಧಿಸಲಾಗಿದೆ. ಈ ಸೈಟ್‌ಗೆ ಮೈಕ್ರೊಫೋನ್ ಅನುಮತಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    micFailed: 'ನಿಮ್ಮ ಧ್ವನಿ ಕೇಳಿಸಲಿಲ್ಲ. ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕ ಪರಿಶೀಲಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ, ಅಥವಾ ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಟೈಪ್ ಮಾಡಿ.',
    heroSubtitleAll: 'AI ಧ್ವನಿ ಮತ್ತು ಪಠ್ಯದ ಮೂಲಕ {count} ಕೇಂದ್ರ ಮತ್ತು ರಾಜ್ಯ ಸರ್ಕಾರದ ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ, ತಕ್ಷಣ ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಅರ್ಜಿ ಮಾರ್ಗದರ್ಶನ ಪಡೆಯಿರಿ.',
    exclusionsTitle: 'ಯಾರು ಅರ್ಹರಲ್ಲ',
    sourcesTitle: 'ಮೂಲಗಳು ಮತ್ತು ಉಲ್ಲೇಖಗಳು',
    sourceCredit: 'ಮೂಲ: myScheme, ಭಾರತ ಸರ್ಕಾರ',
    viewOnMyScheme: 'myScheme ನಲ್ಲಿ ನೋಡಿ',
    noDocs: 'ಅಧಿಕೃತ ಯೋಜನೆ ಪುಟದಲ್ಲಿ ಯಾವುದೇ ದಾಖಲೆಗಳನ್ನು ಪಟ್ಟಿ ಮಾಡಿಲ್ಲ.',
    applyModeLabel: 'ಅರ್ಜಿ ವಿಧಾನ',
    stateScheme: 'ರಾಜ್ಯ ಯೋಜನೆ',
    benefitLabel: 'ಆರ್ಥಿಕ ಪ್ರಯೋಜನ',
    navHome: 'ಮುಖಪುಟ',
    navSchemes: 'ಯೋಜನೆಗಳು',
    navEligibility: 'ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಿ',
    navAskAI: 'AI ಅನ್ನು ಕೇಳಿ',
    brandTagline: 'ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಯೋಜನೆ ಸಹಾಯಕ',
    disclaimer: 'ಸ್ವತಂತ್ರ ನಾಗರಿಕ ಸಹಾಯಕ, ಅಧಿಕೃತ ಸರ್ಕಾರಿ ವೆಬ್‌ಸೈಟ್ ಅಲ್ಲ. ಯಾವಾಗಲೂ ಅಧಿಕೃತ ಯೋಜನೆ ಪೋರ್ಟಲ್‌ನಲ್ಲೇ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ.',
    heroSearchBtn: 'ಹುಡುಕಿ',
    statSchemes: 'ಯೋಜನೆಗಳು',
    statCategories: 'ವರ್ಗಗಳು',
    statLanguages: 'ಭಾಷೆಗಳು',
    homeCtaTitle: 'ಯಾವ ಯೋಜನೆಗಳಿಗೆ ಅರ್ಹರು ಎಂದು ತಿಳಿದಿಲ್ಲವೇ?',
    homeCtaDesc: 'ಕೆಲವು ಸರಳ ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಿಸಿ ಸುಮಾರು 2 ನಿಮಿಷಗಳಲ್ಲಿ ನಿಮ್ಮ ಅರ್ಹತಾ ವರದಿ ಪಡೆಯಿರಿ.',
    homeAskTitle: 'ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲೇ ಕೇಳಿ',
    homeAskDesc: '10 ಭಾರತೀಯ ಭಾಷೆಗಳಲ್ಲಿ ಯಾವುದರಲ್ಲಾದರೂ AI ಸಹಾಯಕರನ್ನು ಟೈಪ್ ಮಾಡಿ ಅಥವಾ ಮಾತನಾಡಿ ಕೇಳಿ.',
    viewAllSchemes: 'ಎಲ್ಲಾ ಯೋಜನೆಗಳನ್ನು ನೋಡಿ',
    viewSchemes: 'ಯೋಜನೆಗಳನ್ನು ನೋಡಿ',
    schemesTitle: 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ',
    schemesSubtitle: 'ವರ್ಗ, ಅರ್ಹತೆ ಮತ್ತು ಪ್ರಯೋಜನಗಳ ಆಧಾರದ ಮೇಲೆ ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ.',
    filtersTitle: 'ಫಿಲ್ಟರ್‌ಗಳು',
    clearFilters: 'ಎಲ್ಲವನ್ನೂ ತೆರವುಗೊಳಿಸಿ',
    filterCategory: 'ವರ್ಗ',
    filterGender: 'ಲಿಂಗ',
    filterSocialCategory: 'ಸಾಮಾಜಿಕ ವರ್ಗ',
    filterOccupation: 'ಉದ್ಯೋಗ',
    filterAny: 'ಯಾವುದಾದರೂ',
    sortBy: 'ವಿಂಗಡಿಸಿ',
    sortRelevance: 'ಸಂಬಂಧಿತ',
    sortBenefit: 'ಅತಿ ಹೆಚ್ಚು ಪ್ರಯೋಜನ',
    sortName: 'ಹೆಸರು (A–Z)',
    resultsCount: '{count} ಯೋಜನೆಗಳು ಸಿಕ್ಕಿವೆ',
    noResults: 'ನಿಮ್ಮ ಹುಡುಕಾಟಕ್ಕೆ ಯಾವುದೇ ಯೋಜನೆ ಸಿಗಲಿಲ್ಲ. ಕೆಲವು ಫಿಲ್ಟರ್‌ಗಳನ್ನು ತೆಗೆದು ನೋಡಿ.',
    viewDetails: 'ವಿವರಗಳನ್ನು ನೋಡಿ',
    backToSchemes: 'ಯೋಜನೆಗಳಿಗೆ ಹಿಂತಿರುಗಿ',
    tabDetails: 'ವಿವರಗಳು',
    tabBenefits: 'ಪ್ರಯೋಜನಗಳು',
    tabEligibility: 'ಅರ್ಹತೆ',
    tabApply: 'ಅರ್ಜಿ ಪ್ರಕ್ರಿಯೆ',
    tabDocuments: 'ಅಗತ್ಯ ದಾಖಲೆಗಳು',
    applyOfficial: 'ಅಧಿಕೃತ ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    checkEligibilityBtn: 'ನಿಮ್ಮ ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಿ',
    listenBtn: 'ಕೇಳಿ',
    stopBtn: 'ನಿಲ್ಲಿಸಿ',
    askAiAbout: 'ಈ ಯೋಜನೆಯ ಬಗ್ಗೆ AI ಅನ್ನು ಕೇಳಿ',
    ministry: 'ಸಚಿವಾಲಯ / ಇಲಾಖೆ',
    schemeLevel: 'ಯೋಜನೆಯ ಮಟ್ಟ',
    officialWebsite: 'ಅಧಿಕೃತ ವೆಬ್‌ಸೈಟ್',
    eligibilityIntro: 'ನೀವು ಈ ಎಲ್ಲಾ ಷರತ್ತುಗಳನ್ನು ಪೂರೈಸಿದರೆ ಅರ್ಹರಾಗಬಹುದು:',
    eligibilityNone: 'ಯಾವುದೇ ವಿಶೇಷ ನಿರ್ಬಂಧಗಳಿಲ್ಲ. ಎಲ್ಲಾ ನಾಗರಿಕರಿಗೆ.',
    eligibilityCheckCta: 'ಖಚಿತವಿಲ್ಲವೇ? ಕೆಲವು ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಿಸಿ ನಿಮ್ಮ ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಿ.',
    docsIntro: 'ನಿಮ್ಮ ಬಳಿ ಇರುವ ದಾಖಲೆಗಳನ್ನು ಗುರುತಿಸಿ, ಇನ್ನೂ ಏನು ಬೇಕು ಎಂದು ತಿಳಿಯುತ್ತದೆ.',
    docsReady: '{total} ರಲ್ಲಿ {ready} ದಾಖಲೆಗಳು ಸಿದ್ಧ',
    docsAllReady: 'ಎಲ್ಲಾ ದಾಖಲೆಗಳು ಸಿದ್ಧ. ಈಗ ಅರ್ಜಿ ಸಲ್ಲಿಸಬಹುದು.',
    applyHelp: 'ಸಹಾಯ ಬೇಕೇ? ಈ ದಾಖಲೆಗಳೊಂದಿಗೆ ಹತ್ತಿರದ ಸಾಮಾನ್ಯ ಸೇವಾ ಕೇಂದ್ರಕ್ಕೆ (CSC) ಹೋಗಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ.',
    quickFacts: 'ಮುಖ್ಯ ಮಾಹಿತಿ',
    notFound: 'ಯೋಜನೆ ಸಿಗಲಿಲ್ಲ.'
  },
  gu: {
    voiceUnavailable: 'આ ઉપકરણ પર {lang} અવાજ ઉપલબ્ધ નથી, તેથી જવાબો લખાણમાં બતાવવામાં આવે છે. અવાજ માટે Microsoft Edge અજમાવો અથવા Windows સેટિંગ્સમાં અવાજ ઉમેરો.',
    micBlocked: 'માઇક્રોફોનની પરવાનગી બંધ છે. આ સાઇટ માટે માઇક્રોફોનની પરવાનગી આપો અને ફરી પ્રયાસ કરો.',
    micFailed: 'તમારો અવાજ સંભળાયો નહીં. ઇન્ટરનેટ કનેક્શન તપાસો અને ફરી પ્રયાસ કરો, અથવા તમારો પ્રશ્ન લખો.',
    heroSubtitleAll: 'AI અવાજ અને ટેક્સ્ટની મદદથી {count} કેન્દ્ર અને રાજ્ય સરકારની યોજનાઓ શોધો, તરત પાત્રતા તપાસો અને અરજી માટે માર્ગદર્શન મેળવો.',
    exclusionsTitle: 'કોણ પાત્ર નથી',
    sourcesTitle: 'સ્રોત અને સંદર્ભો',
    sourceCredit: 'સ્રોત: myScheme, ભારત સરકાર',
    viewOnMyScheme: 'myScheme પર જુઓ',
    noDocs: 'સત્તાવાર યોજના પૃષ્ઠ પર કોઈ દસ્તાવેજો દર્શાવેલ નથી.',
    applyModeLabel: 'અરજીની રીત',
    stateScheme: 'રાજ્ય યોજના',
    benefitLabel: 'આર્થિક લાભ',
    navHome: 'હોમ',
    navSchemes: 'યોજનાઓ',
    navEligibility: 'પાત્રતા તપાસો',
    navAskAI: 'AI ને પૂછો',
    brandTagline: 'તમારી ભાષામાં યોજના સહાયક',
    disclaimer: 'સ્વતંત્ર નાગરિક સહાયક, સત્તાવાર સરકારી વેબસાઇટ નથી. હંમેશા સત્તાવાર યોજના પોર્ટલ પર જ અરજી કરો.',
    heroSearchBtn: 'શોધો',
    statSchemes: 'યોજનાઓ',
    statCategories: 'શ્રેણીઓ',
    statLanguages: 'ભાષાઓ',
    homeCtaTitle: 'કઈ યોજનાઓ માટે પાત્ર છો તે ખબર નથી?',
    homeCtaDesc: 'થોડા સરળ પ્રશ્નોના જવાબ આપો અને લગભગ 2 મિનિટમાં તમારો પાત્રતા અહેવાલ મેળવો.',
    homeAskTitle: 'તમારી ભાષામાં પૂછો',
    homeAskDesc: '10 ભારતીય ભાષાઓમાંથી કોઈપણમાં AI સહાયકને લખીને કે બોલીને પૂછો.',
    viewAllSchemes: 'બધી યોજનાઓ જુઓ',
    viewSchemes: 'યોજનાઓ જુઓ',
    schemesTitle: 'સરકારી યોજનાઓ શોધો',
    schemesSubtitle: 'શ્રેણી, પાત્રતા અને લાભ અનુસાર યોજનાઓ શોધો અને પસંદ કરો.',
    filtersTitle: 'ફિલ્ટર',
    clearFilters: 'બધું દૂર કરો',
    filterCategory: 'શ્રેણી',
    filterGender: 'લિંગ',
    filterSocialCategory: 'સામાજિક વર્ગ',
    filterOccupation: 'વ્યવસાય',
    filterAny: 'કોઈપણ',
    sortBy: 'ક્રમ',
    sortRelevance: 'સુસંગતતા',
    sortBenefit: 'સૌથી વધુ લાભ',
    sortName: 'નામ (A–Z)',
    resultsCount: '{count} યોજનાઓ મળી',
    noResults: 'તમારી શોધ સાથે કોઈ યોજના મેળ ખાતી નથી. કેટલાક ફિલ્ટર દૂર કરી જુઓ.',
    viewDetails: 'વિગતો જુઓ',
    backToSchemes: 'યોજનાઓ પર પાછા',
    tabDetails: 'વિગતો',
    tabBenefits: 'લાભ',
    tabEligibility: 'પાત્રતા',
    tabApply: 'અરજી પ્રક્રિયા',
    tabDocuments: 'જરૂરી દસ્તાવેજો',
    applyOfficial: 'સત્તાવાર પોર્ટલ પર અરજી કરો',
    checkEligibilityBtn: 'તમારી પાત્રતા તપાસો',
    listenBtn: 'સાંભળો',
    stopBtn: 'બંધ કરો',
    askAiAbout: 'આ યોજના વિશે AI ને પૂછો',
    ministry: 'મંત્રાલય / વિભાગ',
    schemeLevel: 'યોજનાનું સ્તર',
    officialWebsite: 'સત્તાવાર વેબસાઇટ',
    eligibilityIntro: 'જો તમે આ બધી શરતો પૂરી કરો તો તમે પાત્ર હોઈ શકો છો:',
    eligibilityNone: 'કોઈ ખાસ શરત નથી. બધા નાગરિકો માટે.',
    eligibilityCheckCta: 'ખાતરી નથી? થોડા પ્રશ્નોના જવાબ આપીને તમારી પાત્રતા તપાસો.',
    docsIntro: 'તમારી પાસે રહેલા દસ્તાવેજો પર નિશાન કરો, જેથી શું બાકી છે તે ખબર પડે.',
    docsReady: '{total} માંથી {ready} દસ્તાવેજો તૈયાર',
    docsAllReady: 'બધા દસ્તાવેજો તૈયાર છે. હવે અરજી કરી શકો છો.',
    applyHelp: 'મદદ જોઈએ છે? આ દસ્તાવેજો સાથે નજીકના કોમન સર્વિસ સેન્ટર (CSC) પર જઈને અરજી કરો.',
    quickFacts: 'મુખ્ય માહિતી',
    notFound: 'યોજના મળી નથી.'
  },
  ml: {
    voiceUnavailable: 'ഈ ഉപകരണത്തിൽ {lang} ശബ്ദം ലഭ്യമല്ല, അതിനാൽ ഉത്തരങ്ങൾ ടെക്സ്റ്റായി കാണിക്കുന്നു. ശബ്ദത്തിനായി Microsoft Edge ഉപയോഗിക്കുക അല്ലെങ്കിൽ Windows ക്രമീകരണങ്ങളിൽ ശബ്ദം ചേർക്കുക.',
    micBlocked: 'മൈക്രോഫോൺ അനുമതി തടഞ്ഞിരിക്കുന്നു. ഈ സൈറ്റിന് മൈക്രോഫോൺ അനുവദിച്ച് വീണ്ടും ശ്രമിക്കുക.',
    micFailed: 'നിങ്ങളുടെ ശബ്ദം കേട്ടില്ല. ഇന്റർനെറ്റ് കണക്ഷൻ പരിശോധിച്ച് വീണ്ടും ശ്രമിക്കുക, അല്ലെങ്കിൽ ചോദ്യം ടൈപ്പ് ചെയ്യുക.',
    heroSubtitleAll: 'AI ശബ്ദവും ടെക്സ്റ്റും ഉപയോഗിച്ച് {count} കേന്ദ്ര, സംസ്ഥാന സർക്കാർ പദ്ധതികൾ കണ്ടെത്തുക, ഉടൻ യോഗ്യത പരിശോധിക്കുക, അപേക്ഷയ്ക്കുള്ള മാർഗ്ഗനിർദ്ദേശം നേടുക.',
    exclusionsTitle: 'ആർക്കാണ് യോഗ്യതയില്ലാത്തത്',
    sourcesTitle: 'സ്രോതസ്സുകളും റഫറൻസുകളും',
    sourceCredit: 'സ്രോതസ്സ്: myScheme, ഭാരത സർക്കാർ',
    viewOnMyScheme: 'myScheme-ൽ കാണുക',
    noDocs: 'ഔദ്യോഗിക പദ്ധതി പേജിൽ രേഖകളൊന്നും നൽകിയിട്ടില്ല.',
    applyModeLabel: 'അപേക്ഷാ രീതി',
    stateScheme: 'സംസ്ഥാന പദ്ധതി',
    benefitLabel: 'സാമ്പത്തിക ആനുകൂല്യം',
    navHome: 'ഹോം',
    navSchemes: 'പദ്ധതികൾ',
    navEligibility: 'യോഗ്യത പരിശോധിക്കുക',
    navAskAI: 'AI-യോട് ചോദിക്കുക',
    brandTagline: 'നിങ്ങളുടെ ഭാഷയിൽ പദ്ധതി സഹായി',
    disclaimer: 'സ്വതന്ത്ര പൗര സഹായി, ഔദ്യോഗിക സർക്കാർ വെബ്സൈറ്റ് അല്ല. എപ്പോഴും ഔദ്യോഗിക പദ്ധതി പോർട്ടലിൽ മാത്രം അപേക്ഷിക്കുക.',
    heroSearchBtn: 'തിരയുക',
    statSchemes: 'പദ്ധതികൾ',
    statCategories: 'വിഭാഗങ്ങൾ',
    statLanguages: 'ഭാഷകൾ',
    homeCtaTitle: 'ഏതൊക്കെ പദ്ധതികൾക്ക് യോഗ്യരാണെന്ന് അറിയില്ലേ?',
    homeCtaDesc: 'ചില ലളിതമായ ചോദ്യങ്ങൾക്ക് ഉത്തരം നൽകി ഏകദേശം 2 മിനിറ്റിനുള്ളിൽ നിങ്ങളുടെ യോഗ്യതാ റിപ്പോർട്ട് നേടുക.',
    homeAskTitle: 'നിങ്ങളുടെ ഭാഷയിൽ ചോദിക്കുക',
    homeAskDesc: '10 ഇന്ത്യൻ ഭാഷകളിൽ ഏതിലും AI സഹായിയോട് ടൈപ്പ് ചെയ്തോ സംസാരിച്ചോ ചോദിക്കുക.',
    viewAllSchemes: 'എല്ലാ പദ്ധതികളും കാണുക',
    viewSchemes: 'പദ്ധതികൾ കാണുക',
    schemesTitle: 'സർക്കാർ പദ്ധതികൾ കണ്ടെത്തുക',
    schemesSubtitle: 'വിഭാഗം, യോഗ്യത, ആനുകൂല്യങ്ങൾ എന്നിവ അനുസരിച്ച് പദ്ധതികൾ തിരയുക.',
    filtersTitle: 'ഫിൽട്ടറുകൾ',
    clearFilters: 'എല്ലാം മായ്ക്കുക',
    filterCategory: 'വിഭാഗം',
    filterGender: 'ലിംഗം',
    filterSocialCategory: 'സാമൂഹിക വിഭാഗം',
    filterOccupation: 'തൊഴിൽ',
    filterAny: 'ഏതും',
    sortBy: 'ക്രമീകരിക്കുക',
    sortRelevance: 'പ്രസക്തി',
    sortBenefit: 'ഏറ്റവും കൂടുതൽ ആനുകൂല്യം',
    sortName: 'പേര് (A–Z)',
    resultsCount: '{count} പദ്ധതികൾ കണ്ടെത്തി',
    noResults: 'നിങ്ങളുടെ തിരയലിന് പൊരുത്തപ്പെടുന്ന പദ്ധതികളില്ല. ചില ഫിൽട്ടറുകൾ നീക്കി നോക്കുക.',
    viewDetails: 'വിശദാംശങ്ങൾ കാണുക',
    backToSchemes: 'പദ്ധതികളിലേക്ക് മടങ്ങുക',
    tabDetails: 'വിശദാംശങ്ങൾ',
    tabBenefits: 'ആനുകൂല്യങ്ങൾ',
    tabEligibility: 'യോഗ്യത',
    tabApply: 'അപേക്ഷാ നടപടി',
    tabDocuments: 'ആവശ്യമായ രേഖകൾ',
    applyOfficial: 'ഔദ്യോഗിക പോർട്ടലിൽ അപേക്ഷിക്കുക',
    checkEligibilityBtn: 'നിങ്ങളുടെ യോഗ്യത പരിശോധിക്കുക',
    listenBtn: 'കേൾക്കുക',
    stopBtn: 'നിർത്തുക',
    askAiAbout: 'ഈ പദ്ധതിയെക്കുറിച്ച് AI-യോട് ചോദിക്കുക',
    ministry: 'മന്ത്രാലയം / വകുപ്പ്',
    schemeLevel: 'പദ്ധതി തലം',
    officialWebsite: 'ഔദ്യോഗിക വെബ്സൈറ്റ്',
    eligibilityIntro: 'ഈ എല്ലാ വ്യവസ്ഥകളും പാലിക്കുന്നുവെങ്കിൽ നിങ്ങൾക്ക് യോഗ്യതയുണ്ടാകാം:',
    eligibilityNone: 'പ്രത്യേക നിയന്ത്രണങ്ങളില്ല. എല്ലാ പൗരന്മാർക്കും.',
    eligibilityCheckCta: 'ഉറപ്പില്ലേ? ചില ചോദ്യങ്ങൾക്ക് ഉത്തരം നൽകി നിങ്ങളുടെ യോഗ്യത പരിശോധിക്കുക.',
    docsIntro: 'നിങ്ങളുടെ കൈവശമുള്ള രേഖകൾ അടയാളപ്പെടുത്തുക, ഇനി എന്താണ് വേണ്ടതെന്ന് അറിയാം.',
    docsReady: '{total} ൽ {ready} രേഖകൾ തയ്യാർ',
    docsAllReady: 'എല്ലാ രേഖകളും തയ്യാർ. ഇപ്പോൾ അപേക്ഷിക്കാം.',
    applyHelp: 'സഹായം വേണോ? ഈ രേഖകളുമായി അടുത്തുള്ള കോമൺ സർവീസ് സെന്ററിൽ (CSC) പോയി അപേക്ഷിക്കുക.',
    quickFacts: 'പ്രധാന വിവരങ്ങൾ',
    notFound: 'പദ്ധതി കണ്ടെത്തിയില്ല.'
  },
  pa: {
    voiceUnavailable: 'ਇਸ ਡਿਵਾਈਸ ਤੇ {lang} ਆਵਾਜ਼ ਉਪਲਬਧ ਨਹੀਂ ਹੈ, ਇਸ ਲਈ ਜਵਾਬ ਟੈਕਸਟ ਵਿੱਚ ਦਿਖਾਏ ਜਾ ਰਹੇ ਹਨ। ਆਵਾਜ਼ ਲਈ Microsoft Edge ਵਰਤੋ ਜਾਂ Windows ਸੈਟਿੰਗਾਂ ਵਿੱਚ ਆਵਾਜ਼ ਜੋੜੋ।',
    micBlocked: 'ਮਾਈਕ੍ਰੋਫ਼ੋਨ ਦੀ ਇਜਾਜ਼ਤ ਬੰਦ ਹੈ। ਇਸ ਸਾਈਟ ਲਈ ਮਾਈਕ੍ਰੋਫ਼ੋਨ ਦੀ ਇਜਾਜ਼ਤ ਦਿਓ ਅਤੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
    micFailed: 'ਤੁਹਾਡੀ ਆਵਾਜ਼ ਸੁਣਾਈ ਨਹੀਂ ਦਿੱਤੀ। ਇੰਟਰਨੈੱਟ ਕਨੈਕਸ਼ਨ ਜਾਂਚੋ ਅਤੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ, ਜਾਂ ਆਪਣਾ ਸਵਾਲ ਲਿਖੋ।',
    heroSubtitleAll: 'AI ਆਵਾਜ਼ ਅਤੇ ਟੈਕਸਟ ਦੀ ਮਦਦ ਨਾਲ {count} ਕੇਂਦਰ ਅਤੇ ਰਾਜ ਸਰਕਾਰ ਦੀਆਂ ਯੋਜਨਾਵਾਂ ਲੱਭੋ, ਤੁਰੰਤ ਯੋਗਤਾ ਜਾਂਚੋ ਅਤੇ ਅਰਜ਼ੀ ਲਈ ਮਾਰਗਦਰਸ਼ਨ ਪ੍ਰਾਪਤ ਕਰੋ।',
    exclusionsTitle: 'ਕੌਣ ਯੋਗ ਨਹੀਂ ਹੈ',
    sourcesTitle: 'ਸਰੋਤ ਅਤੇ ਹਵਾਲੇ',
    sourceCredit: 'ਸਰੋਤ: myScheme, ਭਾਰਤ ਸਰਕਾਰ',
    viewOnMyScheme: 'myScheme ਤੇ ਵੇਖੋ',
    noDocs: 'ਅਧਿਕਾਰਤ ਯੋਜਨਾ ਪੰਨੇ ਤੇ ਕੋਈ ਦਸਤਾਵੇਜ਼ ਸੂਚੀਬੱਧ ਨਹੀਂ ਹਨ।',
    applyModeLabel: 'ਅਰਜ਼ੀ ਦਾ ਤਰੀਕਾ',
    stateScheme: 'ਰਾਜ ਯੋਜਨਾ',
    benefitLabel: 'ਵਿੱਤੀ ਲਾਭ',
    navHome: 'ਮੁੱਖ ਪੰਨਾ',
    navSchemes: 'ਯੋਜਨਾਵਾਂ',
    navEligibility: 'ਯੋਗਤਾ ਜਾਂਚੋ',
    navAskAI: 'AI ਨੂੰ ਪੁੱਛੋ',
    brandTagline: 'ਤੁਹਾਡੀ ਭਾਸ਼ਾ ਵਿੱਚ ਯੋਜਨਾ ਸਹਾਇਕ',
    disclaimer: 'ਸੁਤੰਤਰ ਨਾਗਰਿਕ ਸਹਾਇਕ, ਅਧਿਕਾਰਤ ਸਰਕਾਰੀ ਵੈੱਬਸਾਈਟ ਨਹੀਂ। ਹਮੇਸ਼ਾ ਅਧਿਕਾਰਤ ਯੋਜਨਾ ਪੋਰਟਲ ਤੇ ਹੀ ਅਰਜ਼ੀ ਦਿਓ।',
    heroSearchBtn: 'ਖੋਜੋ',
    statSchemes: 'ਯੋਜਨਾਵਾਂ',
    statCategories: 'ਸ਼੍ਰੇਣੀਆਂ',
    statLanguages: 'ਭਾਸ਼ਾਵਾਂ',
    homeCtaTitle: 'ਪਤਾ ਨਹੀਂ ਕਿਹੜੀਆਂ ਯੋਜਨਾਵਾਂ ਲਈ ਤੁਸੀਂ ਯੋਗ ਹੋ?',
    homeCtaDesc: 'ਕੁਝ ਆਸਾਨ ਸਵਾਲਾਂ ਦੇ ਜਵਾਬ ਦਿਓ ਅਤੇ ਲਗਭਗ 2 ਮਿੰਟਾਂ ਵਿੱਚ ਆਪਣੀ ਯੋਗਤਾ ਰਿਪੋਰਟ ਪ੍ਰਾਪਤ ਕਰੋ।',
    homeAskTitle: 'ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਪੁੱਛੋ',
    homeAskDesc: '10 ਭਾਰਤੀ ਭਾਸ਼ਾਵਾਂ ਵਿੱਚੋਂ ਕਿਸੇ ਵਿੱਚ ਵੀ AI ਸਹਾਇਕ ਨੂੰ ਲਿਖ ਕੇ ਜਾਂ ਬੋਲ ਕੇ ਪੁੱਛੋ।',
    viewAllSchemes: 'ਸਾਰੀਆਂ ਯੋਜਨਾਵਾਂ ਵੇਖੋ',
    viewSchemes: 'ਯੋਜਨਾਵਾਂ ਵੇਖੋ',
    schemesTitle: 'ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ ਲੱਭੋ',
    schemesSubtitle: 'ਸ਼੍ਰੇਣੀ, ਯੋਗਤਾ ਅਤੇ ਲਾਭਾਂ ਅਨੁਸਾਰ ਯੋਜਨਾਵਾਂ ਖੋਜੋ।',
    filtersTitle: 'ਫਿਲਟਰ',
    clearFilters: 'ਸਭ ਹਟਾਓ',
    filterCategory: 'ਸ਼੍ਰੇਣੀ',
    filterGender: 'ਲਿੰਗ',
    filterSocialCategory: 'ਸਮਾਜਿਕ ਵਰਗ',
    filterOccupation: 'ਕਿੱਤਾ',
    filterAny: 'ਕੋਈ ਵੀ',
    sortBy: 'ਕ੍ਰਮ',
    sortRelevance: 'ਪ੍ਰਸੰਗਿਕਤਾ',
    sortBenefit: 'ਸਭ ਤੋਂ ਵੱਧ ਲਾਭ',
    sortName: 'ਨਾਮ (A–Z)',
    resultsCount: '{count} ਯੋਜਨਾਵਾਂ ਮਿਲੀਆਂ',
    noResults: 'ਤੁਹਾਡੀ ਖੋਜ ਨਾਲ ਕੋਈ ਯੋਜਨਾ ਨਹੀਂ ਮਿਲੀ। ਕੁਝ ਫਿਲਟਰ ਹਟਾ ਕੇ ਵੇਖੋ।',
    viewDetails: 'ਵੇਰਵੇ ਵੇਖੋ',
    backToSchemes: 'ਯੋਜਨਾਵਾਂ ਤੇ ਵਾਪਸ',
    tabDetails: 'ਵੇਰਵੇ',
    tabBenefits: 'ਲਾਭ',
    tabEligibility: 'ਯੋਗਤਾ',
    tabApply: 'ਅਰਜ਼ੀ ਪ੍ਰਕਿਰਿਆ',
    tabDocuments: 'ਲੋੜੀਂਦੇ ਦਸਤਾਵੇਜ਼',
    applyOfficial: 'ਅਧਿਕਾਰਤ ਪੋਰਟਲ ਤੇ ਅਰਜ਼ੀ ਦਿਓ',
    checkEligibilityBtn: 'ਆਪਣੀ ਯੋਗਤਾ ਜਾਂਚੋ',
    listenBtn: 'ਸੁਣੋ',
    stopBtn: 'ਰੋਕੋ',
    askAiAbout: 'ਇਸ ਯੋਜਨਾ ਬਾਰੇ AI ਨੂੰ ਪੁੱਛੋ',
    ministry: 'ਮੰਤਰਾਲਾ / ਵਿਭਾਗ',
    schemeLevel: 'ਯੋਜਨਾ ਪੱਧਰ',
    officialWebsite: 'ਅਧਿਕਾਰਤ ਵੈੱਬਸਾਈਟ',
    eligibilityIntro: 'ਜੇ ਤੁਸੀਂ ਇਹ ਸਾਰੀਆਂ ਸ਼ਰਤਾਂ ਪੂਰੀਆਂ ਕਰਦੇ ਹੋ ਤਾਂ ਤੁਸੀਂ ਯੋਗ ਹੋ ਸਕਦੇ ਹੋ:',
    eligibilityNone: 'ਕੋਈ ਖਾਸ ਸ਼ਰਤ ਨਹੀਂ। ਸਾਰੇ ਨਾਗਰਿਕਾਂ ਲਈ।',
    eligibilityCheckCta: 'ਪੱਕਾ ਨਹੀਂ? ਕੁਝ ਸਵਾਲਾਂ ਦੇ ਜਵਾਬ ਦੇ ਕੇ ਆਪਣੀ ਯੋਗਤਾ ਜਾਂਚੋ।',
    docsIntro: 'ਤੁਹਾਡੇ ਕੋਲ ਮੌਜੂਦ ਦਸਤਾਵੇਜ਼ਾਂ ਤੇ ਨਿਸ਼ਾਨ ਲਗਾਓ, ਤਾਂ ਜੋ ਪਤਾ ਲੱਗੇ ਕੀ ਬਾਕੀ ਹੈ।',
    docsReady: '{total} ਵਿੱਚੋਂ {ready} ਦਸਤਾਵੇਜ਼ ਤਿਆਰ',
    docsAllReady: 'ਸਾਰੇ ਦਸਤਾਵੇਜ਼ ਤਿਆਰ ਹਨ। ਹੁਣ ਤੁਸੀਂ ਅਰਜ਼ੀ ਦੇ ਸਕਦੇ ਹੋ।',
    applyHelp: 'ਮਦਦ ਚਾਹੀਦੀ ਹੈ? ਇਹਨਾਂ ਦਸਤਾਵੇਜ਼ਾਂ ਨਾਲ ਨੇੜਲੇ ਕਾਮਨ ਸਰਵਿਸ ਸੈਂਟਰ (CSC) ਤੇ ਜਾ ਕੇ ਅਰਜ਼ੀ ਦਿਓ।',
    quickFacts: 'ਮੁੱਖ ਜਾਣਕਾਰੀ',
    notFound: 'ਯੋਜਨਾ ਨਹੀਂ ਮਿਲੀ।'
  }
};
